"""
ScopeForgeX Nuclei Parser
=========================

Converts Nuclei output into ScopeForgeX Finding objects.

v0.6.1

Input:
    nuclei.txt

Output:
    list[Finding]
"""

from __future__ import annotations

from pathlib import Path

from reporting.findings import Finding


###############################################################################
# Severity Normalization
###############################################################################


def _normalize_severity(
    value: str,
) -> str:
    """
    Normalize nuclei severity values.
    """

    severity = (
        value
        .strip()
        .lower()
    )

    mapping = {
        "critical": "Critical",
        "high": "High",
        "medium": "Medium",
        "low": "Low",
        "info": "Informational",
        "informational": "Informational",
    }

    return mapping.get(
        severity,
        "Informational",
    )


###############################################################################
# Parser
###############################################################################


class NucleiParser:
    """
    Parses Nuclei output files.
    """


    def parse(
        self,
        file_path: str,
    ) -> list[Finding]:
        """
        Parse nuclei findings.
        """

        path = Path(
            file_path
        )

        if not path.exists():

            return []


        findings = []


        with path.open(
            "r",
            encoding="utf-8",
            errors="ignore",
        ) as file:

            for index, line in enumerate(
                file,
                start=1,
            ):

                line = line.strip()


                if not line:

                    continue


                finding = self._parse_line(
                    line,
                    index,
                )


                if finding:

                    findings.append(
                        finding
                    )


        return findings



    ###########################################################################
    # Line Parser
    ###########################################################################

    def _parse_line(
        self,
        line: str,
        index: int,
    ) -> Finding | None:
        """
        Parse single nuclei output line.

        Supports:
            - standard nuclei text output
            - template based output
        """

        parts = line.split()


        if not parts:

            return None


        severity = "Informational"


        for level in (
            "critical",
            "high",
            "medium",
            "low",
            "info",
        ):

            if level in line.lower():

                severity = _normalize_severity(
                    level
                )

                break



        title = parts[0]


        target = (
            parts[-1]
            if len(parts) > 1
            else "unknown"
        )


        return Finding(

            finding_id=f"Nuclei-{index}",

            title=title,

            severity=severity,

            source="nuclei",

            target=target,

            description=(
                "Finding generated by Nuclei scanner."
            ),

            remediation=(
                "Review the affected component "
                "and apply vendor security updates "
                "or configuration fixes."
            ),

        )


###############################################################################
# Convenience Function
###############################################################################


def parse_nuclei(
    file_path: str,
) -> list[Finding]:
    """
    Parse nuclei file.
    """

    return NucleiParser().parse(
        file_path
    )


###############################################################################
# Public API
###############################################################################

__all__ = [
    "NucleiParser",
    "parse_nuclei",
]
