"""
ScopeForgeX Professional Report Generator
==========================================

Generates professional Markdown pentest reports.

v0.6.0

Features:
    - Executive summary
    - Assessment scope
    - Methodology
    - Attack surface summary
    - Risk summary
    - Vulnerability findings
    - Tool execution
    - Artifact tracking
    - Remediation guidance
"""

from __future__ import annotations

from datetime import datetime
from pathlib import Path

from .models import ReportData


###############################################################################
# Report Generator
###############################################################################


class ReportGenerator:
    """
    Markdown report generator.
    """

    TITLE = "ScopeForgeX Assessment Report"


    def __init__(
        self,
        report: ReportData,
    ) -> None:

        self.report = report

        self.lines: list[str] = []


    ###########################################################################
    # Markdown Helpers
    ###########################################################################

    def _line(
        self,
        text: str = "",
    ) -> None:

        self.lines.append(
            f"{text}\n"
        )


    def _blank(
        self,
    ) -> None:

        self.lines.append(
            "\n"
        )


    def _heading(
        self,
        level: int,
        title: str,
    ) -> None:

        self._line(
            f"{'#' * level} {title}"
        )

        self._blank()



    def _bullet(
        self,
        label: str,
        value,
    ) -> None:

        self._line(
            f"- **{label}:** {value}"
        )



    def _table(
        self,
        headers: list[str],
        rows: list[list[str]],
    ) -> None:

        self._line(
            "| "
            + " | ".join(headers)
            + " |"
        )

        self._line(
            "|"
            +
            "|".join(
                "---"
                for _ in headers
            )
            +
            "|"
        )


        for row in rows:

            self._line(
                "| "
                +
                " | ".join(
                    str(item)
                    for item in row
                )
                +
                " |"
            )


        self._blank()



    ###########################################################################
    # Sections
    ###########################################################################

    def _render_title(
        self,
    ) -> None:

        self._heading(
            1,
            self.TITLE,
        )


        self._line(
            "_Generated by ScopeForgeX_"
        )


        self._line(
            datetime.now().strftime(
                "%Y-%m-%d %H:%M:%S"
            )
        )


        self._blank()



    def _render_executive_summary(
        self,
    ) -> None:

        self._heading(
            2,
            "Executive Summary",
        )


        risk = getattr(
            self.report,
            "severity_summary",
            None,
        )


        if risk:

            overall = "Informational"


            if risk.critical:

                overall = "Critical"

            elif risk.high:

                overall = "High"

            elif risk.medium:

                overall = "Medium"

            elif risk.low:

                overall = "Low"


            self._bullet(
                "Overall Risk Rating",
                f"`{overall}`",
            )


        self._bullet(
            "Target",
            f"`{self.report.target}`",
        )


        self._bullet(
            "Profile",
            f"`{self.report.profile}`",
        )


        self._blank()



    def _render_scope(
        self,
    ) -> None:

        self._heading(
            2,
            "Assessment Scope",
        )


        self._bullet(
            "Target",
            self.report.target,
        )


        self._bullet(
            "Target Type",
            self.report.target_type,
        )


        self._blank()



    def _render_methodology(
        self,
    ) -> None:

        self._heading(
            2,
            "Methodology",
        )


        methods = [

            "Reconnaissance",

            "Technology Enumeration",

            "Vulnerability Assessment",

            "Manual Validation Preparation",

            "Reporting",

        ]


        for item in methods:

            self._line(
                f"- {item}"
            )


        self._blank()



    def _render_workflow(
        self,
    ) -> None:

        self._heading(
            2,
            "Workflow Execution",
        )


        rows = []


        for stage in self.report.stages:

            rows.append(
                [
                    stage.name,
                    stage.status,
                ]
            )


        if rows:

            self._table(
                [
                    "Stage",
                    "Status",
                ],
                rows,
            )



    def _render_statistics(
        self,
    ) -> None:

        self._heading(
            2,
            "Attack Surface Summary",
        )


        stats = self.report.statistics


        values = [

            (
                "Subdomains",
                stats.subdomains_found,
            ),

            (
                "Alive Hosts",
                stats.alive_hosts,
            ),

            (
                "URLs",
                stats.urls_discovered,
            ),

            (
                "Vulnerability Findings",
                stats.nuclei_findings,
            ),

            (
                "Files Generated",
                stats.files_generated,
            ),

        ]


        for label, value in values:

            self._bullet(
                label,
                value,
            )


        self._blank()



    def _render_findings(
        self,
    ) -> None:

        self._heading(
            2,
            "Vulnerability Findings",
        )


        if not self.report.findings:

            self._line(
                "No automated vulnerabilities were identified."
            )

            self._blank()

            return



        rows = []


        for finding in self.report.findings:

            rows.append(
                [
                    finding.finding_id,

                    finding.severity,

                    finding.title,

                    finding.source,

                    finding.target,

                ]
            )


        self._table(
            [
                "ID",
                "Severity",
                "Title",
                "Source",
                "Target",
            ],
            rows,
        )



    def _render_risk_summary(
        self,
    ) -> None:

        self._heading(
            2,
            "Risk Summary",
        )


        summary = (
            self.report.severity_summary
        )


        rows = [

            [
                "Critical",
                summary.critical,
            ],

            [
                "High",
                summary.high,
            ],

            [
                "Medium",
                summary.medium,
            ],

            [
                "Low",
                summary.low,
            ],

            [
                "Informational",
                summary.informational,
            ],

        ]


        self._table(
            [
                "Severity",
                "Count",
            ],
            rows,
        )



    def _render_tools(
        self,
    ) -> None:

        if not self.report.tool_results:

            return


        self._heading(
            2,
            "Tool Execution",
        )


        rows = []


        for tool, status in self.report.tool_results.items():

            rows.append(
                [
                    tool,
                    status,
                ]
            )


        self._table(
            [
                "Tool",
                "Status",
            ],
            rows,
        )



    def _render_artifacts(
        self,
    ) -> None:

        self._heading(
            2,
            "Generated Artifacts",
        )


        for artifact in self.report.generated_files:

            self._line(
                f"- `{artifact}`"
            )


        self._blank()



    def _render_remediation(
        self,
    ) -> None:

        self._heading(
            2,
            "Remediation Guidance",
        )


        if not self.report.findings:

            self._line(
                "No remediation actions required from automated findings."
            )


        else:

            for finding in self.report.findings:

                self._line(
                    f"- **{finding.title}:** {finding.remediation}"
                )


        self._blank()



    def _render_notes(
        self,
    ) -> None:

        if not self.report.warnings:

            return


        self._heading(
            2,
            "Execution Notes",
        )


        for warning in self.report.warnings:

            self._line(
                f"- {warning}"
            )


        self._blank()



    ###########################################################################
    # Public API
    ###########################################################################

    def generate_markdown(
        self,
        output_file: str,
    ) -> None:


        self.lines.clear()


        self._render_title()

        self._render_executive_summary()

        self._render_scope()

        self._render_methodology()

        self._render_workflow()

        self._render_statistics()

        self._render_findings()

        self._render_risk_summary()

        self._render_tools()

        self._render_artifacts()

        self._render_remediation()

        self._render_notes()


        Path(
            output_file
        ).write_text(
            "".join(
                self.lines
            ),
            encoding="utf-8",
        )



###############################################################################
# Public API
###############################################################################


__all__ = [
    "ReportGenerator",
]
