"""
ScopeForgeX Report Generator
============================

Generates Markdown reports from ReportData.

Design Goals
------------
* Fully backward compatible
* Modular section rendering
* Easy HTML/PDF extension
* Clean Markdown formatting
* Future-ready architecture

v0.4.0
"""

from __future__ import annotations

from pathlib import Path
from datetime import datetime

from .models import ReportData


###############################################################################
# Report Generator
###############################################################################


class ReportGenerator:
    """
    Markdown report generator.

    The report is constructed incrementally using reusable rendering
    methods. This makes future HTML/PDF exporters significantly easier
    because only the renderer changes while the data model remains
    identical.
    """

    TITLE = "ScopeForgeX Assessment Report"

    def __init__(
        self,
        report: ReportData,
    ) -> None:

        self.report = report
        self.lines: list[str] = []

    ###########################################################################
    # Basic Markdown Helpers
    ###########################################################################

    def _line(
        self,
        text: str = "",
    ) -> None:
        self.lines.append(f"{text}\n")

    def _blank(self) -> None:
        self.lines.append("\n")

    def _heading(
        self,
        level: int,
        title: str,
    ) -> None:

        self._line(
            f'{"#" * level} {title}'
        )
        self._blank()

    def _bullet(
        self,
        label: str,
        value,
    ) -> None:

        self._line(
            f"- **{label}:** {value}"
        )

    def _table(
        self,
        headers: list[str],
        rows: list[list[str]],
    ) -> None:

        self._line(
            "| "
            + " | ".join(headers)
            + " |"
        )

        self._line(
            "|"
            + "|".join(
                "---"
                for _ in headers
            )
            + "|"
        )

        for row in rows:
            self._line(
                "| "
                + " | ".join(
                    str(col)
                    for col in row
                )
                + " |"
            )

        self._blank()

    ###########################################################################
    # Rendering Sections
    ###########################################################################

    def _render_title(self) -> None:

        self._heading(
            1,
            self.TITLE,
        )

        self._line(
            "_Generated by ScopeForgeX_"
        )

        self._line(
            datetime.now().strftime(
                "%Y-%m-%d %H:%M:%S"
            )
        )

        self._blank()

    def _render_summary(self) -> None:

        r = self.report

        self._heading(
            2,
            "Assessment Summary",
        )

        self._bullet(
            "Target",
            f"`{r.target}`",
        )

        self._bullet(
            "Profile",
            f"`{r.profile}`",
        )

        self._bullet(
            "Target Type",
            f"`{r.target_type}`",
        )

        if getattr(
            r,
            "start_time",
            None,
        ):
            self._bullet(
                "Started",
                r.start_time,
            )

        if getattr(
            r,
            "end_time",
            None,
        ):
            self._bullet(
                "Finished",
                r.end_time,
            )

        if hasattr(
            r,
            "duration_seconds",
        ):
            self._bullet(
                "Duration",
                f"{r.duration_seconds:.2f} seconds",
            )

        self._blank()
    def _render_workflow(self) -> None:
        """
        Render workflow execution summary.
        """

        self._heading(
            2,
            "Workflow Execution",
        )

        rows: list[list[str]] = []

        for stage in getattr(
            self.report,
            "stages",
            [],
        ):
            rows.append(
                [
                    stage.name,
                    stage.status,
                ]
            )

        if rows:
            self._table(
                [
                    "Stage",
                    "Status",
                ],
                rows,
            )
        else:
            self._line(
                "_No workflow information available._"
            )
            self._blank()

    ###########################################################################
    # Statistics
    ###########################################################################

    def _render_statistics(self) -> None:
        """
        Render workflow statistics.
        """

        stats = self.report.statistics

        self._heading(
            2,
            "Workflow Statistics",
        )

        metrics = [
            (
                "Subdomains discovered",
                stats.subdomains_found,
            ),
            (
                "Alive hosts",
                stats.alive_hosts,
            ),
            (
                "Validated hosts",
                stats.final_hosts,
            ),
            (
                "URLs discovered",
                stats.urls_discovered,
            ),
            (
                "Nuclei findings",
                stats.nuclei_findings,
            ),
            (
                "Files generated",
                stats.files_generated,
            ),
        ]

        for label, value in metrics:
            self._bullet(
                label,
                f"**{value}**",
            )

        self._blank()

    ###########################################################################
    # Tool Execution
    ###########################################################################

    def _render_tools(self) -> None:
        """
        Render tool execution results.
        """

        tool_results = getattr(
            self.report,
            "tool_results",
            None,
        )

        if not tool_results:
            return

        self._heading(
            2,
            "Tool Execution",
        )

        rows = []

        for tool, status in tool_results.items():
            rows.append(
                [
                    tool,
                    status,
                ]
            )

        self._table(
            [
                "Tool",
                "Status",
            ],
            rows,
        )

    ###########################################################################
    # Generated Artifacts
    ###########################################################################

    def _render_artifacts(self) -> None:
        """
        Render generated files.
        """

        if not self.report.generated_files:
            return

        self._heading(
            2,
            "Generated Artifacts",
        )

        for artifact in self.report.generated_files:
            self._line(
                f"- `{Path(artifact).name}`"
            )

        self._blank()

    ###########################################################################
    # Execution Notes
    ###########################################################################

    def _render_notes(self) -> None:
        """
        Render warnings and execution notes.
        """

        warnings = getattr(
            self.report,
            "warnings",
            None,
        )

        if not warnings:
            return

        self._heading(
            2,
            "Execution Notes",
        )

        for warning in warnings:
            self._line(
                f"- {warning}"
            )

        self._blank()
    ###########################################################################
    # Analyst Guidance
    ###########################################################################

    def _render_guidance(self) -> None:
        """
        Render analyst recommendations.
        """

        self._heading(
            2,
            "Analyst Guidance",
        )

        guidance = [
            "Review all automated findings before reporting them.",
            "Investigate medium and high severity findings manually.",
            "Verify potential false positives.",
            "Review skipped stages and failed tools.",
            "Correlate findings across multiple tools.",
            "Re-run using the FULL_SAFE profile if broader coverage is required.",
        ]

        for item in guidance:
            self._line(
                f"- {item}"
            )

        self._blank()

    ###########################################################################
    # Public API
    ###########################################################################

    def generate_markdown(
        self,
        output_file: str,
    ) -> None:
        """
        Generate a Markdown report.

        Parameters
        ----------
        output_file:
            Destination Markdown file.
        """

        self.lines.clear()

        self._render_title()
        self._render_summary()
        self._render_workflow()
        self._render_statistics()
        self._render_tools()
        self._render_artifacts()
        self._render_notes()
        self._render_guidance()

        Path(output_file).write_text(
            "".join(self.lines),
            encoding="utf-8",
        )

    ###########################################################################
    # Future Extension Hooks
    ###########################################################################

    def generate_html(
        self,
        output_file: str,
    ) -> None:
        """
        Placeholder for a future HTML report exporter.

        The Markdown generator remains the canonical implementation in
        v0.4.0. HTML/PDF generation can reuse the same rendering model
        without changing the ReportData structure.
        """

        raise NotImplementedError(
            "HTML report generation is planned for a future release."
        )


###############################################################################
# Module Exports
###############################################################################

__all__ = [
    "ReportGenerator",
]
