"""
ScopeForgeX Nmap Collector
==========================

Normalizes Nmap XML output into ScopeForgeX collector observations.

Nmap is the primary network discovery tool in the frozen ScopeForgeX
architecture.

Primary assessment capabilities
--------------------------------

- Port discovery
- Port state detection
- Service detection
- Service version detection
- Operating-system hints
- NSE script findings
- Network configuration observations

Normalized observation types
----------------------------

- OPEN_PORT
- SERVICE
- SERVICE_VERSION
- NETWORK_CONFIGURATION
- NSE_SECURITY_FINDING

The collector only parses already-generated Nmap evidence.

It does not:

- Execute Nmap.
- Perform network requests.
- Construct Nmap commands.
- Decide whether an observation is a confirmed vulnerability.
- Discard the original Nmap evidence.

Raw Nmap output remains available through the execution artifact and is
attached to observations where practical.

Input
-----

The collector accepts Nmap XML artifacts generated by the ScopeForgeX
execution layer.

Expected artifact names include:

    nmap.xml
    nmap_output.xml
    nmap_scan.xml

The collector also supports execution results that expose an XML artifact
through the standard CollectorBase artifact interface.

Design Principles
-----------------

- Nmap is the canonical network discovery tool in ScopeForgeX.
- XML is preferred because it provides structured, machine-readable output.
- Invalid XML is ignored rather than crashing the complete assessment.
- Hosts, ports and services are represented as independent observations.
- Closed and filtered ports are not reported as OPEN_PORT observations.
- Service observations are emitted when service information exists.
- Version observations are emitted when version information exists.
- NSE script output is preserved as evidence.
- Script output is not automatically classified as a confirmed vulnerability.
- Observation confidence describes parsing/detection confidence, not exploit
  confirmation.
- Target context from the workflow is preserved.
- Correlation and deduplication remain downstream responsibilities.

v1.0.0
"""

from __future__ import annotations

import xml.etree.ElementTree as ET
from pathlib import Path
from typing import Any, Mapping

from scopeforgex.collectors.base import (
    CollectorBase,
    CollectorObservation,
)


###############################################################################
# Constants
###############################################################################


NMAP_TOOL = "nmap"

OBSERVATION_OPEN_PORT = "OPEN_PORT"
OBSERVATION_SERVICE = "SERVICE"
OBSERVATION_SERVICE_VERSION = "SERVICE_VERSION"
OBSERVATION_NETWORK_CONFIGURATION = "NETWORK_CONFIGURATION"
OBSERVATION_NSE_SECURITY_FINDING = "NSE_SECURITY_FINDING"

NMAP_XML_ARTIFACT_NAMES = (
    "nmap.xml",
    "nmap_output.xml",
    "nmap_scan.xml",
)


###############################################################################
# Nmap Collector
###############################################################################


class NmapCollector(CollectorBase):
    """
    Collect structured observations from Nmap XML output.

    The collector deliberately keeps parsing separate from execution.
    Nmap command construction belongs to the Nmap tool adapter and process
    execution belongs to the ScopeForgeX runtime.
    """

    name = "nmap_collector"

    tool = NMAP_TOOL

    description = (
        "Collect ports, services, versions, network configuration and NSE "
        "observations from Nmap XML output."
    )

    ###########################################################################
    # Public API
    ###########################################################################

    def parse(
        self,
        execution_result: Any,
        ctx: Mapping[str, Any],
    ) -> list[CollectorObservation]:
        """
        Parse all Nmap XML evidence artifacts.

        Args:
            execution_result:
                Execution-layer result containing Nmap artifacts.

            ctx:
                Shared ScopeForgeX workflow context.

        Returns:
            A list of normalized CollectorObservation objects.

        Invalid or unreadable XML artifacts are skipped so that one malformed
        artifact does not prevent other assessment evidence from being
        processed.
        """

        observations: list[CollectorObservation] = []

        for artifact in self.get_artifacts(
            execution_result
        ):
            if not self._is_nmap_xml_artifact(
                artifact
            ):
                continue

            path = self._artifact_path(
                artifact
            )

            if path is None:
                continue

            observations.extend(
                self._parse_xml_file(
                    path,
                    ctx,
                )
            )

        return observations

    ###########################################################################
    # Artifact Helpers
    ###########################################################################

    @staticmethod
    def _is_nmap_xml_artifact(
        artifact: Any,
    ) -> bool:
        """
        Determine whether an execution artifact is an Nmap XML artifact.
        """

        name = str(
            getattr(
                artifact,
                "name",
                "",
            )
        ).strip().lower()

        if name in NMAP_XML_ARTIFACT_NAMES:
            return True

        return name.endswith(
            ".xml"
        ) and (
            "nmap" in name
        )

    @staticmethod
    def _artifact_path(
        artifact: Any,
    ) -> Path | None:
        """
        Extract a filesystem path from an execution artifact.
        """

        for field_name in (
            "path",
            "file_path",
            "filepath",
        ):
            value = getattr(
                artifact,
                field_name,
                None,
            )

            if value:
                return Path(
                    value
                )

        return None

    ###########################################################################
    # XML Parsing
    ###########################################################################

    def _parse_xml_file(
        self,
        path: Path,
        ctx: Mapping[str, Any],
    ) -> list[CollectorObservation]:
        """
        Parse one Nmap XML file.
        """

        try:
            root = ET.parse(
                path
            ).getroot()
        except (
            ET.ParseError,
            OSError,
            ValueError,
        ):
            return []

        observations: list[CollectorObservation] = []

        for host in root.findall(
            ".//host"
        ):
            observations.extend(
                self._parse_host(
                    host,
                    ctx,
                    path,
                )
            )

        return observations

    ###########################################################################
    # Host Parsing
    ###########################################################################

    def _parse_host(
        self,
        host_element: ET.Element,
        ctx: Mapping[str, Any],
        source_path: Path,
    ) -> list[CollectorObservation]:
        """
        Parse one Nmap host element.
        """

        observations: list[CollectorObservation] = []

        host = self._extract_host(
            host_element
        )

        if not host:
            host = self._context_host(
                ctx
            )

        if not host:
            return observations

        status = host_element.find(
            "./status"
        )

        host_state = self._attribute(
            status,
            "state",
        )

        if host_state:
            observations.append(
                self._host_status_observation(
                    host,
                    host_state,
                    ctx,
                    source_path,
                )
            )

        observations.extend(
            self._parse_ports(
                host_element,
                host,
                ctx,
                source_path,
            )
        )

        observations.extend(
            self._parse_host_scripts(
                host_element,
                host,
                ctx,
                source_path,
            )
        )

        return observations

    @staticmethod
    def _extract_host(
        host_element: ET.Element,
    ) -> str:
        """
        Extract the preferred host address.

        IPv4/IPv6 addresses are preferred over hostnames because they provide
        a stable network-asset identity.
        """

        addresses = host_element.findall(
            "./address"
        )

        preferred_types = (
            "ipv4",
            "ipv6",
            "mac",
        )

        for address_type in preferred_types:
            for address in addresses:
                if (
                    address.attrib.get(
                        "addrtype",
                        "",
                    ).lower()
                    == address_type
                ):
                    value = address.attrib.get(
                        "addr",
                        "",
                    ).strip()

                    if value:
                        return value

        hostname = host_element.find(
            "./hostnames/hostname"
        )

        return (
            hostname.attrib.get(
                "name",
                "",
            ).strip()
            if hostname is not None
            else ""
        )

    ###########################################################################
    # Host Status
    ###########################################################################

    def _host_status_observation(
        self,
        host: str,
        state: str,
        ctx: Mapping[str, Any],
        source_path: Path,
    ) -> CollectorObservation:
        """
        Build a network configuration observation for host state.
        """

        return CollectorObservation(
            observation_type=OBSERVATION_NETWORK_CONFIGURATION,
            value=state,
            target=ctx.get(
                "target"
            ),
            host=host,
            evidence={
                "host_state": state,
                "artifact": str(
                    source_path
                ),
            },
            source_tool=self.tool,
            detection_method="nmap_host_status",
            confidence="high",
            metadata={
                "state": state,
            },
        )

    ###########################################################################
    # Port Parsing
    ###########################################################################

    def _parse_ports(
        self,
        host_element: ET.Element,
        host: str,
        ctx: Mapping[str, Any],
        source_path: Path,
    ) -> list[CollectorObservation]:
        """
        Parse ports, states and service metadata.
        """

        observations: list[CollectorObservation] = []

        for port_element in host_element.findall(
            "./ports/port"
        ):
            port = self._port_number(
                port_element
            )

            if port is None:
                continue

            protocol = (
                port_element.attrib.get(
                    "protocol",
                    "",
                ).strip().lower()
                or None
            )

            state_element = port_element.find(
                "./state"
            )

            state = self._attribute(
                state_element,
                "state",
            ).lower()

            if state == "open":
                observations.append(
                    self._open_port_observation(
                        host=host,
                        port=port,
                        protocol=protocol,
                        state_element=state_element,
                        ctx=ctx,
                        source_path=source_path,
                    )
                )

            if state != "open":
                continue

            service_element = port_element.find(
                "./service"
            )

            if service_element is None:
                continue

            service_name = self._attribute(
                service_element,
                "name",
            )

            product = self._attribute(
                service_element,
                "product",
            )

            version = self._attribute(
                service_element,
                "version",
            )

            extrainfo = self._attribute(
                service_element,
                "extrainfo",
            )

            if service_name:
                observations.append(
                    self._service_observation(
                        host=host,
                        port=port,
                        protocol=protocol,
                        service_element=service_element,
                        ctx=ctx,
                        source_path=source_path,
                    )
                )

            if (
                product
                or version
                or extrainfo
            ):
                observations.append(
                    self._service_version_observation(
                        host=host,
                        port=port,
                        protocol=protocol,
                        service_element=service_element,
                        ctx=ctx,
                        source_path=source_path,
                    )
                )

            observations.extend(
                self._parse_port_scripts(
                    port_element=port_element,
                    host=host,
                    port=port,
                    protocol=protocol,
                    ctx=ctx,
                    source_path=source_path,
                )
            )

        return observations

    ###########################################################################
    # Open Port
    ###########################################################################

    def _open_port_observation(
        self,
        *,
        host: str,
        port: int,
        protocol: str | None,
        state_element: ET.Element | None,
        ctx: Mapping[str, Any],
        source_path: Path,
    ) -> CollectorObservation:
        """
        Build an OPEN_PORT observation.
        """

        evidence = {
            "state": self._attribute(
                state_element,
                "state",
            ),
            "reason": self._attribute(
                state_element,
                "reason",
            ),
            "reason_ttl": self._attribute(
                state_element,
                "reason_ttl",
            ),
            "artifact": str(
                source_path
            ),
        }

        metadata = {
            "protocol": protocol,
            "state": "open",
        }

        return CollectorObservation(
            observation_type=OBSERVATION_OPEN_PORT,
            value=str(
                port
            ),
            target=ctx.get(
                "target"
            ),
            host=host,
            port=port,
            evidence=evidence,
            source_tool=self.tool,
            detection_method="nmap_port_state",
            confidence="high",
            metadata=metadata,
        )

    ###########################################################################
    # Service
    ###########################################################################

    def _service_observation(
        self,
        *,
        host: str,
        port: int,
        protocol: str | None,
        service_element: ET.Element,
        ctx: Mapping[str, Any],
        source_path: Path,
    ) -> CollectorObservation:
        """
        Build a SERVICE observation.
        """

        service_name = self._attribute(
            service_element,
            "name",
        )

        evidence = {
            "name": service_name,
            "product": self._attribute(
                service_element,
                "product",
            ),
            "version": self._attribute(
                service_element,
                "version",
            ),
            "extrainfo": self._attribute(
                service_element,
                "extrainfo",
            ),
            "method": self._attribute(
                service_element,
                "method",
            ),
            "conf": self._attribute(
                service_element,
                "conf",
            ),
            "artifact": str(
                source_path
            ),
        }

        return CollectorObservation(
            observation_type=OBSERVATION_SERVICE,
            value=service_name,
            target=ctx.get(
                "target"
            ),
            host=host,
            port=port,
            evidence=evidence,
            source_tool=self.tool,
            detection_method="nmap_service_detection",
            confidence="high",
            metadata={
                "protocol": protocol,
                "service": service_name,
            },
        )

    ###########################################################################
    # Service Version
    ###########################################################################

    def _service_version_observation(
        self,
        *,
        host: str,
        port: int,
        protocol: str | None,
        service_element: ET.Element,
        ctx: Mapping[str, Any],
        source_path: Path,
    ) -> CollectorObservation:
        """
        Build a SERVICE_VERSION observation.
        """

        product = self._attribute(
            service_element,
            "product",
        )

        version = self._attribute(
            service_element,
            "version",
        )

        extrainfo = self._attribute(
            service_element,
            "extrainfo",
        )

        components = [
            value
            for value in (
                product,
                version,
                extrainfo,
            )
            if value
        ]

        value = " ".join(
            components
        )

        return CollectorObservation(
            observation_type=OBSERVATION_SERVICE_VERSION,
            value=value,
            target=ctx.get(
                "target"
            ),
            host=host,
            port=port,
            evidence={
                "product": product,
                "version": version,
                "extrainfo": extrainfo,
                "cpe": self._attribute(
                    service_element,
                    "cpe",
                ),
                "artifact": str(
                    source_path
                ),
            },
            source_tool=self.tool,
            detection_method="nmap_service_version",
            confidence="high",
            metadata={
                "protocol": protocol,
                "product": product,
                "version": version,
                "extrainfo": extrainfo,
            },
        )

    ###########################################################################
    # NSE Scripts
    ###########################################################################

    def _parse_port_scripts(
        self,
        *,
        port_element: ET.Element,
        host: str,
        port: int,
        protocol: str | None,
        ctx: Mapping[str, Any],
        source_path: Path,
    ) -> list[CollectorObservation]:
        """
        Parse NSE script output attached to an individual port.

        Script output is represented as an assessment observation. It is not
        automatically considered a confirmed vulnerability.
        """

        observations: list[CollectorObservation] = []

        for script in port_element.findall(
            "./script"
        ):
            observation = self._script_observation(
                script=script,
                host=host,
                port=port,
                protocol=protocol,
                ctx=ctx,
                source_path=source_path,
                scope="port",
            )

            if observation is not None:
                observations.append(
                    observation
                )

        return observations

    def _parse_host_scripts(
        self,
        *,
        host_element: ET.Element,
        host: str,
        ctx: Mapping[str, Any],
        source_path: Path,
    ) -> list[CollectorObservation]:
        """
        Parse NSE script output attached directly to a host.
        """

        observations: list[CollectorObservation] = []

        for script in host_element.findall(
            "./hostscript/script"
        ):
            observation = self._script_observation(
                script=script,
                host=host,
                port=None,
                protocol=None,
                ctx=ctx,
                source_path=source_path,
                scope="host",
            )

            if observation is not None:
                observations.append(
                    observation
                )

        return observations

    def _script_observation(
        self,
        *,
        script: ET.Element,
        host: str,
        port: int | None,
        protocol: str | None,
        ctx: Mapping[str, Any],
        source_path: Path,
        scope: str,
    ) -> CollectorObservation | None:
        """
        Convert one NSE script result into an observation.
        """

        script_id = self._attribute(
            script,
            "id",
        )

        output = self._attribute(
            script,
            "output",
        )

        if not script_id and not output:
            return None

        value = (
            script_id
            or "NSE script result"
        )

        metadata = {
            "script_id": script_id,
            "scope": scope,
            "protocol": protocol,
        }

        evidence = {
            "script_id": script_id,
            "output": output,
            "artifact": str(
                source_path
            ),
            "xml": self._element_to_dict(
                script
            ),
        }

        return CollectorObservation(
            observation_type=OBSERVATION_NSE_SECURITY_FINDING,
            value=value,
            target=ctx.get(
                "target"
            ),
            host=host,
            port=port,
            evidence=evidence,
            source_tool=self.tool,
            detection_method="nmap_nse",
            confidence="medium",
            metadata=metadata,
        )

    ###########################################################################
    # XML Helpers
    ###########################################################################

    @staticmethod
    def _attribute(
        element: ET.Element | None,
        name: str,
    ) -> str:
        """
        Safely retrieve an XML attribute.
        """

        if element is None:
            return ""

        return str(
            element.attrib.get(
                name,
                "",
            )
        ).strip()

    @staticmethod
    def _port_number(
        port_element: ET.Element,
    ) -> int | None:
        """
        Convert an Nmap port attribute into an integer.
        """

        value = port_element.attrib.get(
            "portid"
        )

        if value is None:
            return None

        try:
            return int(
                value
            )
        except (
            TypeError,
            ValueError,
        ):
            return None

    @staticmethod
    def _context_host(
        ctx: Mapping[str, Any],
    ) -> str:
        """
        Retrieve a host value from workflow context.
        """

        for field_name in (
            "host",
            "target",
        ):
            value = ctx.get(
                field_name
            )

            if value:
                return str(
                    value
                ).strip()

        return ""

    ###########################################################################
    # XML Evidence Serialization
    ###########################################################################

    @classmethod
    def _element_to_dict(
        cls,
        element: ET.Element,
    ) -> dict[str, Any]:
        """
        Convert an XML element into a JSON-compatible dictionary.

        This preserves nested NSE table/list output while keeping the
        observation evidence serializable.
        """

        result: dict[str, Any] = {
            "tag": element.tag,
        }

        if element.attrib:
            result[
                "attributes"
            ] = dict(
                element.attrib
            )

        text = (
            element.text.strip()
            if element.text
            and element.text.strip()
            else ""
        )

        if text:
            result[
                "text"
            ] = text

        children: list[dict[str, Any]] = []

        for child in element:
            children.append(
                cls._element_to_dict(
                    child
                )
            )

        if children:
            result[
                "children"
            ] = children

        return result


###############################################################################
# Public Exports
###############################################################################


__all__ = [
    "NMAP_TOOL",
    "OBSERVATION_OPEN_PORT",
    "OBSERVATION_SERVICE",
    "OBSERVATION_SERVICE_VERSION",
    "OBSERVATION_NETWORK_CONFIGURATION",
    "OBSERVATION_NSE_SECURITY_FINDING",
    "NmapCollector",
]
