"""
ScopeForgeX Nmap Collector
==========================

Normalizes Nmap XML output into ScopeForgeX collector observations.

Nmap is the primary network discovery tool in the frozen ScopeForgeX
architecture.

Primary assessment capabilities
--------------------------------

- Port discovery
- Port state detection
- Service detection
- Service version detection
- Operating-system hints
- NSE script findings
- Network configuration observations

Normalized observation types
----------------------------

- OPEN_PORT
- SERVICE
- SERVICE_VERSION
- NETWORK_CONFIGURATION
- NSE_SECURITY_FINDING

The collector only parses already-generated Nmap evidence.

It does not:

- Execute Nmap.
- Perform network requests.
- Construct Nmap commands.
- Decide whether an observation is a confirmed vulnerability.
- Discard the original Nmap evidence.

Raw Nmap output remains available through the execution artifact and is
attached to observations where practical.

Input
-----

The collector accepts Nmap XML artifacts generated by the ScopeForgeX
execution layer.

Expected artifact names include:

    nmap.xml
    nmap_output.xml
    nmap_scan.xml

The collector also supports execution results that expose an XML artifact
through the standard CollectorBase artifact interface.

Design Principles
-----------------

- Nmap is the canonical network discovery tool in ScopeForgeX.
- XML is preferred because it provides structured, machine-readable output.
- Invalid XML is ignored rather than crashing the complete assessment.
- Hosts, ports and services are represented as independent observations.
- Closed and filtered ports are not reported as OPEN_PORT observations.
- Service observations are emitted when service information exists.
- Version observations are emitted when version information exists.
- NSE script output is preserved as evidence.
- Script output is not automatically classified as a confirmed vulnerability.
- Observation confidence describes parsing/detection confidence, not exploit
  confirmation.
- Target context from the workflow is preserved.
- Correlation and deduplication remain downstream responsibilities.

v1.0.0
"""

from __future__ import annotations

import xml.etree.ElementTree as ET
from pathlib import Path
from typing import Any, Mapping

from scopeforgex.collectors.base import (
    CollectorBase,
    CollectorObservation,
)


###############################################################################
# Constants
###############################################################################


NMAP_TOOL = "nmap"

OBSERVATION_OPEN_PORT = "OPEN_PORT"
OBSERVATION_SERVICE = "SERVICE"
OBSERVATION_SERVICE_VERSION = "SERVICE_VERSION"
OBSERVATION_NETWORK_CONFIGURATION = "NETWORK_CONFIGURATION"
OBSERVATION_NSE_SECURITY_FINDING = "NSE_SECURITY_FINDING"

NMAP_XML_ARTIFACT_NAMES = (
    "nmap.xml",
    "nmap_output.xml",
    "nmap_scan.xml",
)


###############################################################################
# Nmap Collector
###############################################################################


class NmapCollector(CollectorBase):
    """
    Collect structured observations from Nmap XML output.

    The collector deliberately keeps parsing separate from execution.
    Nmap command construction belongs to the Nmap tool adapter and process
    execution belongs to the ScopeForgeX runtime.
    """

    name = "nmap_collector"

    tool = NMAP_TOOL

    description = (
        "Collect ports, services, versions, network configuration and NSE "
        "observations from Nmap XML output."
    )

    ###########################################################################
    # Public API
    ###########################################################################

    def parse(
        self,
        execution_result: Any,
        ctx: Mapping[str, Any],
    ) -> list[CollectorObservation]:
        """
        Parse all Nmap XML evidence artifacts.

        Args:
            execution_result:
                Execution-layer result containing Nmap artifacts.

            ctx:
                Shared ScopeForgeX workflow context.

        Returns:
            A list of normalized CollectorObservation objects.

        Invalid or unreadable XML artifacts are skipped so that one malformed
        artifact does not prevent other assessment evidence from being
        processed.
        """

        observations: list[CollectorObservation] = []

        for artifact in self.get_artifacts(
            execution_result
        ):
            if not self._is_nmap_xml_artifact(
                artifact
            ):
                continue

            path = self._artifact_path(
                artifact
            )

            if path is None:
                continue

            observations.extend(
                self._parse_xml_file(
                    path,
                    ctx,
                )
            )

        return observations

    ###########################################################################
    # Artifact Helpers
    ###########################################################################

    @staticmethod
    def _is_nmap_xml_artifact(
        artifact: Any,
    ) -> bool:
        """
        Determine whether an execution artifact is an Nmap XML artifact.

        ExecutionResult stores artifacts as filesystem path strings. The
        collector also accepts artifact-like objects exposing a ``name``
        attribute for compatibility with other execution paths.
        """

        if isinstance(
            artifact,
            (str, Path),
        ):
            name = Path(
                artifact
            ).name.strip().lower()

        else:
            name = str(
                getattr(
                    artifact,
                    "name",
                    "",
                )
            ).strip().lower()

        if name in NMAP_XML_ARTIFACT_NAMES:
            return True

        return name.endswith(
            ".xml"
        ) and (
            "nmap" in name
        )

    @staticmethod
    def _artifact_path(
        artifact: Any,
    ) -> Path | None:
        """
        Extract a filesystem path from an execution artifact.

        ExecutionResult uses ``list[str]`` for artifacts, while some runtime
        paths may expose artifact objects with path-like attributes.
        """

        if isinstance(
            artifact,
            (str, Path),
        ):
            value = str(
                artifact
            ).strip()

            return (
                Path(value)
                if value
                else None
            )

        for field_name in (
            "path",
            "file_path",
            "filepath",
        ):
            value = getattr(
                artifact,
                field_name,
                None,
            )

            if value:
                return Path(
                    value
                )

        return None

    ###########################################################################
    # XML Parsing
    ###########################################################################

    def _parse_xml_file(
        self,
        path: Path,
        ctx: Mapping[str, Any],
    ) -> list[CollectorObservation]:
        """
        Parse one Nmap XML file.
        """

        try:
            root = ET.parse(
                path
            ).getroot()
        except (
            ET.ParseError,
            OSError,
            ValueError,
        ):
            return []

        observations: list[CollectorObservation] = []

        for host in root.findall(
            ".//host"
        ):
            observations.extend(
                self._parse_host(
                    host,
                    ctx,
                    path,
                )
            )

        return observations

    ###########################################################################
    # Host Parsing
    ###########################################################################

    def _parse_host(
        self,
        host_element: ET.Element,
        ctx: Mapping[str, Any],
        source_path: Path,
    ) -> list[CollectorObservation]:
        """
        Parse one Nmap host element.
        """

        observations: list[CollectorObservation] = []

        host = self._extract_host(
            host_element
        )

        if not host:
            host = self._context_host(
                ctx
            )

        if not host:
            return observations

        status = host_element.find(
            "./status"
        )

        host_state = self._attribute(
            status,
            "state",
        )

        if host_state:
            observations.append(
                self._host_status_observation(
                    host,
                    host_state,
                    source_path,
                )
            )

        observations.extend(
            self._parse_ports(
                host_element,
                host,
                ctx,
                source_path,
            )
        )

        observations.extend(
            self._parse_host_scripts(
                host_element,
                host,
                source_path,
            )
        )

        return observations

    @staticmethod
    def _extract_host(
        host_element: ET.Element,
    ) -> str:
        """
        Extract the preferred host address.

        IPv4/IPv6 addresses are preferred over hostnames because they provide
        deterministic network asset identity.
        """

        addresses = host_element.findall(
            "./address"
        )

        for address in addresses:
            address_type = str(
                address.attrib.get(
                    "addrtype",
                    "",
                )
            ).strip().lower()

            if address_type in {
                "ipv4",
                "ipv6",
            }:
                value = str(
                    address.attrib.get(
                        "addr",
                        "",
                    )
                ).strip()

                if value:
                    return value

        for address in addresses:
            value = str(
                address.attrib.get(
                    "addr",
                    "",
                )
            ).strip()

            if value:
                return value

        hostname = host_element.find(
            "./hostnames/hostname"
        )

        if hostname is not None:
            return str(
                hostname.attrib.get(
                    "name",
                    "",
                )
            ).strip()

        return ""

    ###########################################################################
    # Host Status
    ###########################################################################

    def _host_status_observation(
        self,
        host: str,
        state: str,
        source_path: Path,
    ) -> CollectorObservation:
        """
        Build a network configuration observation for host state.
        """

        return CollectorObservation(
            observation_type=OBSERVATION_NETWORK_CONFIGURATION,
            value=state,
            title=f"Nmap host state: {state}",
            description=(
                f"Nmap reported host {host} as {state}."
            ),
            severity="Informational",
            confidence="High",
            status="Observed",
            host=host,
            evidence={
                "source": str(
                    source_path
                ),
                "host_state": state,
            },
            source_tool=NMAP_TOOL,
            detection_method="nmap_host_status",
        )

    ###########################################################################
    # Port Parsing
    ###########################################################################

    def _parse_ports(
        self,
        host_element: ET.Element,
        host: str,
        ctx: Mapping[str, Any],
        source_path: Path,
    ) -> list[CollectorObservation]:
        """
        Parse ports, states and service metadata.
        """

        observations: list[CollectorObservation] = []

        for port_element in host_element.findall(
            "./ports/port"
        ):
            port = self._port_number(
                port_element
            )

            if port is None:
                continue

            state_element = port_element.find(
                "./state"
            )

            state = self._attribute(
                state_element,
                "state",
            )

            if state == "open":
                observations.append(
                    self._open_port_observation(
                        host=host,
                        port=port,
                        port_element=port_element,
                        source_path=source_path,
                    )
                )

            service_element = port_element.find(
                "./service"
            )

            if service_element is None:
                continue

            service_name = self._attribute(
                service_element,
                "name",
            )

            product = self._attribute(
                service_element,
                "product",
            )

            version = self._attribute(
                service_element,
                "version",
            )

            extrainfo = self._attribute(
                service_element,
                "extrainfo",
            )

            cpe = self._attribute(
                service_element,
                "cpe",
            )

            if service_name:
                observations.append(
                    self._service_observation(
                        host=host,
                        port=port,
                        service_element=service_element,
                        source_path=source_path,
                    )
                )

            if (
                product
                or version
                or cpe
            ):
                observations.append(
                    self._service_version_observation(
                        host=host,
                        port=port,
                        service_element=service_element,
                        source_path=source_path,
                    )
                )

            if port_element.findall(
                "./script"
            ):
                observations.extend(
                    self._parse_port_scripts(
                        port_element=port_element,
                        host=host,
                        port=port,
                        source_path=source_path,
                    )
                )

        return observations

    ###########################################################################
    # Open Port
    ###########################################################################

    def _open_port_observation(
        self,
        host: str,
        port: int,
        port_element: ET.Element,
        source_path: Path,
    ) -> CollectorObservation:
        """
        Build an open-port observation.
        """

        state_element = port_element.find(
            "./state"
        )

        state = self._attribute(
            state_element,
            "state",
        )

        return CollectorObservation(
            observation_type=OBSERVATION_OPEN_PORT,
            value=f"{host}:{port}",
            title=f"Open port {host}:{port}",
            description=(
                f"Nmap reported TCP/UDP port {port} on {host} "
                f"as {state or 'open'}."
            ),
            severity="Informational",
            confidence="High",
            status="Observed",
            host=host,
            port=port,
            evidence={
                "source": str(
                    source_path
                ),
                "state": state,
                "protocol": (
                    port_element.attrib.get(
                        "protocol"
                    )
                ),
            },
            source_tool=NMAP_TOOL,
            detection_method="nmap_port_state",
        )

    ###########################################################################
    # Service
    ###########################################################################

    def _service_observation(
        self,
        host: str,
        port: int,
        service_element: ET.Element,
        source_path: Path,
    ) -> CollectorObservation:
        """
        Build a service observation.
        """

        service_name = self._attribute(
            service_element,
            "name",
        )

        return CollectorObservation(
            observation_type=OBSERVATION_SERVICE,
            value=service_name,
            title=(
                f"Detected service: {service_name}"
            ),
            description=(
                f"Nmap identified service {service_name} on "
                f"{host}:{port}."
            ),
            severity="Informational",
            confidence=self._service_confidence(
                service_element
            ),
            status="Observed",
            host=host,
            port=port,
            evidence={
                "source": str(
                    source_path
                ),
                "service": service_name,
                "product": self._attribute(
                    service_element,
                    "product",
                ),
                "version": self._attribute(
                    service_element,
                    "version",
                ),
                "extrainfo": self._attribute(
                    service_element,
                    "extrainfo",
                ),
                "method": self._attribute(
                    service_element,
                    "method",
                ),
                "conf": self._attribute(
                    service_element,
                    "conf",
                ),
            },
            source_tool=NMAP_TOOL,
            detection_method="nmap_service_detection",
            metadata={
                "service": service_name,
                "product": self._attribute(
                    service_element,
                    "product",
                ),
                "version": self._attribute(
                    service_element,
                    "version",
                ),
                "cpe": self._attribute(
                    service_element,
                    "cpe",
                ),
            },
        )

    ###########################################################################
    # Service Version
    ###########################################################################

    def _service_version_observation(
        self,
        host: str,
        port: int,
        service_element: ET.Element,
        source_path: Path,
    ) -> CollectorObservation:
        """
        Build a service/version observation.
        """

        product = self._attribute(
            service_element,
            "product",
        )

        version = self._attribute(
            service_element,
            "version",
        )

        service_name = self._attribute(
            service_element,
            "name",
        )

        cpe = self._attribute(
            service_element,
            "cpe",
        )

        value_parts = [
            part
            for part in (
                product,
                version,
            )
            if part
        ]

        value = " ".join(
            value_parts
        )

        if not value:
            value = (
                service_name
                or cpe
                or "unknown"
            )

        return CollectorObservation(
            observation_type=OBSERVATION_SERVICE_VERSION,
            value=value,
            title=(
                f"Detected service version: {value}"
            ),
            description=(
                f"Nmap reported service/version information for "
                f"{host}:{port}."
            ),
            severity="Informational",
            confidence=self._service_confidence(
                service_element
            ),
            status="Observed",
            host=host,
            port=port,
            evidence={
                "source": str(
                    source_path
                ),
                "service": service_name,
                "product": product,
                "version": version,
                "extrainfo": self._attribute(
                    service_element,
                    "extrainfo",
                ),
                "cpe": cpe,
            },
            source_tool=NMAP_TOOL,
            detection_method="nmap_service_version",
            metadata={
                "service": service_name,
                "product": product,
                "version": version,
                "cpe": cpe,
            },
        )

    ###########################################################################
    # NSE Scripts
    ###########################################################################

    def _parse_port_scripts(
        self,
        port_element: ET.Element,
        host: str,
        port: int,
        source_path: Path,
    ) -> list[CollectorObservation]:
        """
        Parse NSE script output attached to an individual port.
        """

        observations: list[CollectorObservation] = []

        for script in port_element.findall(
            "./script"
        ):
            observations.append(
                self._script_observation(
                    script=script,
                    host=host,
                    port=port,
                    source_path=source_path,
                    scope="port",
                )
            )

        return observations

    def _parse_host_scripts(
        self,
        host_element: ET.Element,
        host: str,
        source_path: Path,
    ) -> list[CollectorObservation]:
        """
        Parse NSE script output attached directly to a host.
        """

        observations: list[CollectorObservation] = []

        for script in host_element.findall(
            "./hostscript/script"
        ):
            observations.append(
                self._script_observation(
                    script=script,
                    host=host,
                    port=None,
                    source_path=source_path,
                    scope="host",
                )
            )

        return observations

    def _script_observation(
        self,
        script: ET.Element,
        host: str,
        port: int | None,
        source_path: Path,
        scope: str,
    ) -> CollectorObservation:
        """
        Preserve an NSE script result as a structured observation.
        """

        script_id = self._attribute(
            script,
            "id",
        )

        output = self._attribute(
            script,
            "output",
        )

        value = (
            output
            or script_id
            or "NSE script result"
        )

        return CollectorObservation(
            observation_type=OBSERVATION_NSE_SECURITY_FINDING,
            value=value,
            title=(
                f"Nmap NSE result: {script_id or 'unknown'}"
            ),
            description=(
                "Nmap NSE script output preserved as assessment evidence. "
                "The result is not automatically treated as a confirmed "
                "vulnerability."
            ),
            severity="Informational",
            confidence="Medium",
            status="Observed",
            host=host,
            port=port,
            evidence={
                "source": str(
                    source_path
                ),
                "scope": scope,
                "script_id": script_id,
                "output": output,
                "xml": self._element_to_dict(
                    script
                ),
            },
            source_tool=NMAP_TOOL,
            detection_method="nmap_nse",
            metadata={
                "script_id": script_id,
                "scope": scope,
            },
        )

    ###########################################################################
    # Generic Helpers
    ###########################################################################

    @staticmethod
    def _attribute(
        element: ET.Element | None,
        name: str,
    ) -> str:
        """
        Return a stripped XML attribute value.
        """

        if element is None:
            return ""

        return str(
            element.attrib.get(
                name,
                "",
            )
        ).strip()

    @staticmethod
    def _port_number(
        port_element: ET.Element,
    ) -> int | None:
        """
        Convert an Nmap port attribute into an integer.
        """

        value = port_element.attrib.get(
            "portid"
        )

        if value is None:
            return None

        try:
            return int(
                value
            )
        except (
            TypeError,
            ValueError,
        ):
            return None

    @staticmethod
    def _context_host(
        ctx: Mapping[str, Any],
    ) -> str:
        """
        Retrieve a host value from workflow context.
        """

        for key in (
            "host",
            "target_host",
            "target",
        ):
            value = ctx.get(
                key
            )

            if value:
                return str(
                    value
                ).strip()

        return ""

    @staticmethod
    def _service_confidence(
        service_element: ET.Element,
    ) -> str:
        """
        Convert Nmap service confidence into ScopeForgeX confidence.
        """

        value = service_element.attrib.get(
            "conf"
        )

        try:
            confidence = int(
                str(
                    value
                )
            )
        except (
            TypeError,
            ValueError,
        ):
            return "Medium"

        if confidence >= 7:
            return "High"

        if confidence >= 4:
            return "Medium"

        return "Low"

    @staticmethod
    def _element_to_dict(
        element: ET.Element,
    ) -> dict[str, Any]:
        """
        Convert an XML element into a JSON-compatible dictionary.
        """

        result: dict[str, Any] = {
            "tag": element.tag,
            "attributes": dict(
                element.attrib
            ),
        }

        children: list[dict[str, Any]] = []

        for child in element:
            children.append(
                NmapCollector._element_to_dict(
                    child
                )
            )

        if children:
            result["children"] = children

        text = (
            element.text or ""
        ).strip()

        if text:
            result["text"] = text

        return result


###############################################################################
# Public Exports
###############################################################################


__all__ = [
    "NmapCollector",
]
