"""
ScopeForgeX Cookie Security Analyzer
====================================

Native analyzer for evaluating HTTP cookie security attributes.

The analyzer consumes HTTP response evidence collected by ScopeForgeX and
produces normalized observations for the universal Finding pipeline.

Responsibilities
----------------

- Analyze Set-Cookie response headers without invoking an external tool.
- Detect missing Secure attributes.
- Detect missing HttpOnly attributes.
- Detect weak or missing SameSite configuration.
- Preserve cookie name and relevant security attributes as evidence.
- Produce deterministic, structured observations.
- Keep detection separate from correlation, deduplication, and final reporting.

Analyzed Attributes
-------------------

- Secure
- HttpOnly
- SameSite
- Domain
- Path

Architecture
------------

HTTP Response Evidence
        |
        v
   Cookie Analyzer
        |
        v
Normalized Observations
        |
        v
 Finding Normalizer
        |
        v
Correlation / Risk Engine
        |
        v
      Report

Design Principles
-----------------

- The analyzer performs no network requests.
- The analyzer does not execute external tools.
- Cookie values are never included in normalized evidence.
- Missing attributes are observations and are not automatically treated as
  critical vulnerabilities.
- SameSite evaluation is context-sensitive and therefore conservative.
- Domain and Path attributes are retained as metadata for downstream analysis.
- One cookie can generate multiple independent security observations.
- The analyzer performs local deduplication only.
- Final correlation, deduplication, and risk classification remain outside
  this analyzer.

v1.0.0
"""

from __future__ import annotations

import re
from dataclasses import dataclass, field
from typing import Any, Iterable, Mapping


###############################################################################
# Constants
###############################################################################


ANALYZER_NAME = "cookies"

CATEGORY_INSECURE = "INSECURE_COOKIE"
CATEGORY_HTTPONLY = "MISSING_HTTPONLY"
CATEGORY_SECURE = "MISSING_SECURE"
CATEGORY_SAMESITE = "WEAK_SAMESITE"

DEFAULT_SEVERITY = "Medium"
DEFAULT_CONFIDENCE = "High"

DETECTION_METHOD = "Native HTTP Cookie Security Analysis"


###############################################################################
# Observation
###############################################################################


@dataclass(slots=True)
class CookieObservation:
    """
    Structured observation generated by the native cookie analyzer.
    """

    title: str

    description: str

    category: str

    target: str = ""

    host: str | None = None

    url: str | None = None

    cookie_name: str | None = None

    severity: str = DEFAULT_SEVERITY

    confidence: str = DEFAULT_CONFIDENCE

    source_tool: str = ANALYZER_NAME

    detection_method: str = DETECTION_METHOD

    evidence: dict[str, Any] = field(
        default_factory=dict
    )

    metadata: dict[str, Any] = field(
        default_factory=dict
    )

    cwe: str | None = None

    references: list[str] = field(
        default_factory=list
    )

    impact: str = ""

    remediation: str = ""

    def as_dict(self) -> dict[str, Any]:
        """
        Convert the observation into a mapping suitable for the universal
        finding-normalization layer.
        """

        metadata = dict(
            self.metadata
        )

        if self.cookie_name:
            metadata.setdefault(
                "cookie_name",
                self.cookie_name,
            )

        return {
            "title": self.title,
            "category": self.category,
            "target": self.target,
            "host": self.host,
            "url": self.url,
            "description": self.description,
            "severity": self.severity,
            "confidence": self.confidence,
            "evidence": dict(self.evidence),
            "source_tool": self.source_tool,
            "detection_method": self.detection_method,
            "cwe": self.cwe,
            "references": list(
                self.references
            ),
            "impact": self.impact,
            "remediation": self.remediation,
            "metadata": metadata,
        }


###############################################################################
# Analyzer
###############################################################################


class CookieAnalyzer:
    """
    Analyze Set-Cookie response headers.

    The analyzer accepts raw Set-Cookie values, response mappings, or common
    HTTP response objects. It never performs network activity itself.
    """

    name = ANALYZER_NAME

    description = (
        "Analyze HTTP cookies for missing or weak security attributes."
    )

    ###########################################################################
    # Public API
    ###########################################################################

    def analyze(
        self,
        response: Any = None,
        *,
        target: str = "",
        set_cookie: Any = None,
        cookies: Any = None,
        headers: Mapping[str, Any] | None = None,
        **kwargs: Any,
    ) -> list[CookieObservation]:
        """
        Analyze cookies from an HTTP response.

        Parameters
        ----------
        response:
            Optional response object or mapping.

        target:
            Target URL or asset identifier.

        set_cookie:
            Explicit Set-Cookie value or collection of Set-Cookie values.

        cookies:
            Explicit cookie header values. This is accepted as an alias for
            set_cookie.

        headers:
            Optional HTTP response headers. Set-Cookie values are extracted
            from these headers when explicit cookie input is absent.

        Returns
        -------
        list[CookieObservation]
            Structured cookie-security observations.
        """

        effective_target = (
            target
            or self._extract_response_url(
                response
            )
            or ""
        )

        raw_values = self._collect_set_cookie_values(
            set_cookie=set_cookie,
            cookies=cookies,
            headers=headers,
            response=response,
        )

        if not raw_values:
            return []

        observations: list[CookieObservation] = []

        for raw_cookie in raw_values:

            parsed = self._parse_set_cookie(
                raw_cookie
            )

            if parsed is None:
                continue

            observations.extend(
                self._analyze_cookie(
                    parsed,
                    target=effective_target,
                )
            )

        return self._deduplicate(
            observations
        )

    ###########################################################################
    # Cookie analysis
    ###########################################################################

    def _analyze_cookie(
        self,
        cookie: Mapping[str, Any],
        *,
        target: str,
    ) -> list[CookieObservation]:
        """
        Analyze a single parsed Set-Cookie record.
        """

        name = cookie.get(
            "name"
        )

        if not name:
            return []

        secure = bool(
            cookie.get(
                "secure",
                False,
            )
        )

        httponly = bool(
            cookie.get(
                "httponly",
                False,
            )
        )

        samesite = cookie.get(
            "samesite"
        )

        domain = cookie.get(
            "domain"
        )

        path = cookie.get(
            "path"
        )

        observations: list[CookieObservation] = []

        is_https = self._is_https(
            target
        )

        #######################################################################
        # Secure
        #######################################################################

        if is_https and not secure:
            observations.append(
                self._build_observation(
                    category=CATEGORY_SECURE,
                    title=(
                        f"Missing Secure attribute on cookie '{name}'"
                    ),
                    description=(
                        f"The cookie '{name}' is set by an HTTPS target "
                        "without the Secure attribute."
                    ),
                    target=target,
                    cookie=cookie,
                    severity="Medium",
                    impact=(
                        "Without Secure, the browser may send the cookie over "
                        "an unencrypted HTTP connection if such a connection "
                        "is available, increasing exposure to interception."
                    ),
                    remediation=(
                        "Set the Secure attribute on cookies that should only "
                        "be transmitted over HTTPS."
                    ),
                    cwe="CWE-614",
                )
            )

        #######################################################################
        # HttpOnly
        #######################################################################

        if not httponly:
            observations.append(
                self._build_observation(
                    category=CATEGORY_HTTPONLY,
                    title=(
                        f"Missing HttpOnly attribute on cookie '{name}'"
                    ),
                    description=(
                        f"The cookie '{name}' does not define the HttpOnly "
                        "attribute."
                    ),
                    target=target,
                    cookie=cookie,
                    severity="Medium",
                    impact=(
                        "Client-side scripts may be able to access the cookie. "
                        "If an attacker can execute JavaScript in the "
                        "application context, the cookie may become accessible."
                    ),
                    remediation=(
                        "Set HttpOnly on authentication and other sensitive "
                        "cookies that do not require JavaScript access."
                    ),
                    cwe="CWE-1004",
                )
            )

        #######################################################################
        # SameSite
        #######################################################################

        if not samesite:
            observations.append(
                self._build_observation(
                    category=CATEGORY_SAMESITE,
                    title=(
                        f"Missing SameSite attribute on cookie '{name}'"
                    ),
                    description=(
                        f"The cookie '{name}' does not explicitly define "
                        "a SameSite policy."
                    ),
                    target=target,
                    cookie=cookie,
                    severity="Low",
                    impact=(
                        "The absence of an explicit SameSite policy can reduce "
                        "control over cross-site cookie transmission and may "
                        "increase exposure to cross-site request scenarios."
                    ),
                    remediation=(
                        "Set an explicit SameSite value appropriate for the "
                        "application. Prefer Strict or Lax where compatible "
                        "with application behavior; use None only when "
                        "cross-site cookie delivery is intentionally required."
                    ),
                    cwe="CWE-352",
                )
            )

        elif str(
            samesite
        ).lower() == "none":
            if not secure:
                observations.append(
                    self._build_observation(
                        category=CATEGORY_SAMESITE,
                        title=(
                            f"Insecure SameSite=None cookie '{name}'"
                        ),
                        description=(
                            f"The cookie '{name}' explicitly uses "
                            "SameSite=None without Secure."
                        ),
                        target=target,
                        cookie=cookie,
                        severity="Medium",
                        impact=(
                            "A cross-site cookie configured with SameSite=None "
                            "without Secure may not be accepted or may fail "
                            "to provide the intended security properties."
                        ),
                        remediation=(
                            "When SameSite=None is required, configure the "
                            "cookie with Secure and ensure cross-site delivery "
                            "is intentional."
                        ),
                        cwe="CWE-352",
                    )
                )

        #######################################################################
        # Domain
        #######################################################################

        if domain:
            normalized_domain = str(
                domain
            ).strip()

            if normalized_domain.startswith("."):
                observations.append(
                    self._build_observation(
                        category=CATEGORY_INSECURE,
                        title=(
                            f"Broad cookie Domain scope on '{name}'"
                        ),
                        description=(
                            f"The cookie '{name}' uses the broad Domain "
                            f"attribute '{normalized_domain}'."
                        ),
                        target=target,
                        cookie=cookie,
                        severity="Low",
                        impact=(
                            "A broadly scoped cookie may be sent to multiple "
                            "subdomains. If a less-trusted subdomain is "
                            "compromised, the cookie may become exposed."
                        ),
                        remediation=(
                            "Use the narrowest Domain scope required by the "
                            "application and avoid unnecessarily sharing "
                            "sensitive cookies across subdomains."
                        ),
                        cwe="CWE-565",
                    )
                )

        #######################################################################
        # Path
        #######################################################################

        if path:
            normalized_path = str(
                path
            ).strip()

            if normalized_path == "/":
                observations.append(
                    self._build_observation(
                        category=CATEGORY_INSECURE,
                        title=(
                            f"Broad cookie Path scope on '{name}'"
                        ),
                        description=(
                            f"The cookie '{name}' is scoped to the root "
                            "application path."
                        ),
                        target=target,
                        cookie=cookie,
                        severity="Low",
                        impact=(
                            "A root-scoped cookie is sent to all matching "
                            "application paths. For sensitive cookies, a "
                            "narrower scope may reduce unnecessary exposure."
                        ),
                        remediation=(
                            "Use the narrowest Path scope compatible with "
                            "the application's requirements."
                        ),
                        cwe="CWE-565",
                    )
                )

        return observations

    ###########################################################################
    # Cookie parsing
    ###########################################################################

    @staticmethod
    def _parse_set_cookie(
        value: Any,
    ) -> dict[str, Any] | None:
        """
        Parse one Set-Cookie header.

        Cookie values are deliberately not retained. Only the cookie name and
        security-relevant attributes are extracted.
        """

        raw = str(
            value
            or ""
        ).strip()

        if not raw:
            return None

        parts = [
            part.strip()
            for part in raw.split(";")
            if part.strip()
        ]

        if not parts:
            return None

        first = parts[0]

        if "=" not in first:
            return None

        name, _cookie_value = first.split(
            "=",
            1,
        )

        name = name.strip()

        if not name:
            return None

        parsed: dict[str, Any] = {
            "name": name,
            "secure": False,
            "httponly": False,
            "samesite": None,
            "domain": None,
            "path": None,
        }

        for attribute in parts[1:]:

            if "=" in attribute:
                key, attribute_value = attribute.split(
                    "=",
                    1,
                )

                key = key.strip().lower()
                attribute_value = attribute_value.strip()

                if key == "samesite":
                    parsed["samesite"] = (
                        attribute_value.lower()
                    )

                elif key == "domain":
                    parsed["domain"] = (
                        attribute_value
                    )

                elif key == "path":
                    parsed["path"] = (
                        attribute_value
                    )

                continue

            normalized = attribute.lower()

            if normalized == "secure":
                parsed["secure"] = True

            elif normalized == "httponly":
                parsed["httponly"] = True

        return parsed

    ###########################################################################
    # Input extraction
    ###########################################################################

    @classmethod
    def _collect_set_cookie_values(
        cls,
        *,
        set_cookie: Any,
        cookies: Any,
        headers: Mapping[str, Any] | None,
        response: Any,
    ) -> list[str]:
        """
        Collect Set-Cookie values from explicit arguments, headers, or a
        response object.
        """

        source = (
            set_cookie
            if set_cookie is not None
            else cookies
        )

        if source is None:
            source = cls._extract_set_cookie_from_headers(
                headers
            )

        if source is None:
            source = cls._extract_set_cookie_from_headers(
                cls._extract_headers(
                    response
                )
            )

        return cls._normalize_cookie_values(
            source
        )

    @staticmethod
    def _normalize_cookie_values(
        values: Any,
    ) -> list[str]:
        """
        Normalize cookie input into individual Set-Cookie strings.

        A list/tuple is treated as multiple headers. A single string remains
        a single header because commas may legitimately occur in attributes
        such as Expires.
        """

        if values is None:
            return []

        if isinstance(
            values,
            bytes,
        ):
            values = values.decode(
                "utf-8",
                errors="replace",
            )

        if isinstance(
            values,
            str,
        ):
            return [
                values
            ] if values.strip() else []

        if isinstance(
            values,
            Iterable,
        ):
            result: list[str] = []

            for value in values:

                normalized = str(
                    value
                ).strip()

                if normalized:
                    result.append(
                        normalized
                    )

            return result

        normalized = str(
            values
        ).strip()

        return (
            [normalized]
            if normalized
            else []
        )

    @staticmethod
    def _extract_set_cookie_from_headers(
        headers: Mapping[str, Any] | None,
    ) -> Any:
        """Extract Set-Cookie from a header mapping."""

        if not headers:
            return None

        for key, value in headers.items():

            if str(
                key
            ).strip().lower() == "set-cookie":
                return value

        return None

    @staticmethod
    def _extract_headers(
        response: Any,
    ) -> Mapping[str, Any] | None:
        """Extract headers from common response representations."""

        if response is None:
            return None

        if isinstance(
            response,
            Mapping,
        ):
            headers = response.get(
                "headers"
            )

            if isinstance(
                headers,
                Mapping,
            ):
                return headers

            return None

        headers = getattr(
            response,
            "headers",
            None,
        )

        if isinstance(
            headers,
            Mapping,
        ):
            return headers

        return None

    @staticmethod
    def _extract_response_url(
        response: Any,
    ) -> str:
        """Extract response URL where available."""

        if response is None:
            return ""

        if isinstance(
            response,
            Mapping,
        ):
            return str(
                response.get(
                    "url",
                    ""
                )
                or ""
            ).strip()

        return str(
            getattr(
                response,
                "url",
                ""
            )
            or ""
        ).strip()

    ###########################################################################
    # Observation factory
    ###########################################################################

    @staticmethod
    def _build_observation(
        *,
        category: str,
        title: str,
        description: str,
        target: str,
        cookie: Mapping[str, Any],
        severity: str,
        impact: str,
        remediation: str,
        cwe: str | None,
    ) -> CookieObservation:
        """
        Build a normalized cookie observation.

        The cookie value is intentionally excluded from evidence.
        """

        cookie_name = str(
            cookie.get(
                "name",
                ""
            )
        ).strip()

        safe_attributes = {
            "secure": bool(
                cookie.get(
                    "secure",
                    False,
                )
            ),
            "httponly": bool(
                cookie.get(
                    "httponly",
                    False,
                )
            ),
            "samesite": cookie.get(
                "samesite"
            ),
            "domain": cookie.get(
                "domain"
            ),
            "path": cookie.get(
                "path"
            ),
        }

        return CookieObservation(
            title=title,
            description=description,
            category=category,
            target=target,
            host=CookieAnalyzer._extract_host(
                target
            ),
            url=(
                target
                if CookieAnalyzer._is_url(
                    target
                )
                else None
            ),
            cookie_name=cookie_name,
            severity=severity,
            confidence=DEFAULT_CONFIDENCE,
            evidence={
                "cookie_name": cookie_name,
                "attributes": safe_attributes,
                "cookie_value": "[REDACTED]",
            },
            metadata={
                "analyzer": ANALYZER_NAME,
                "observation_type": category.lower(),
            },
            cwe=cwe,
            impact=impact,
            remediation=remediation,
        )

    ###########################################################################
    # Target helpers
    ###########################################################################

    @staticmethod
    def _is_https(
        target: str,
    ) -> bool:
        """Return True when target is an HTTPS URL."""

        return bool(
            re.match(
                r"^https://",
                str(
                    target
                ).strip(),
                flags=re.IGNORECASE,
            )
        )

    @staticmethod
    def _is_url(
        target: str | None,
    ) -> bool:
        """Return True when target is an HTTP(S) URL."""

        if not target:
            return False

        return bool(
            re.match(
                r"^https?://",
                str(
                    target
                ).strip(),
                flags=re.IGNORECASE,
            )
        )

    @staticmethod
    def _extract_host(
        target: str | None,
    ) -> str | None:
        """Extract hostname from an HTTP(S) URL."""

        if not target:
            return None

        match = re.match(
            r"^https?://([^/:?#]+)",
            str(
                target
            ).strip(),
            flags=re.IGNORECASE,
        )

        if not match:
            return None

        return match.group(1)

    ###########################################################################
    # Deduplication
    ###########################################################################

    @staticmethod
    def _deduplicate(
        observations: list[CookieObservation],
    ) -> list[CookieObservation]:
        """
        Remove duplicate observations for the same cookie/category/target.
        """

        unique: list[CookieObservation] = []
        seen: set[tuple[str, str, str]] = set()

        for observation in observations:

            key = (
                observation.target,
                observation.category,
                observation.cookie_name or "",
            )

            if key in seen:
                continue

            seen.add(key)
            unique.append(
                observation
            )

        return unique


###############################################################################
# Compatibility aliases
###############################################################################


Analyzer = CookieAnalyzer


###############################################################################
# Public API
###############################################################################


__all__ = [
    "CookieAnalyzer",
    "CookieObservation",
    "Analyzer",
    "ANALYZER_NAME",
    "CATEGORY_INSECURE",
    "CATEGORY_HTTPONLY",
    "CATEGORY_SECURE",
    "CATEGORY_SAMESITE",
    "DETECTION_METHOD",
]
