"""
ScopeForgeX Cookie Security Analyzer
====================================

Native analyzer for evaluating HTTP cookie security attributes.

The analyzer consumes HTTP response evidence collected by ScopeForgeX and
produces normalized observations for the universal Finding pipeline.

Responsibilities
----------------

- Analyze Set-Cookie response headers without invoking an external tool.
- Detect missing Secure attributes.
- Detect missing HttpOnly attributes.
- Detect weak or missing SameSite configuration.
- Preserve cookie name and relevant security attributes as evidence.
- Produce deterministic, structured observations.
- Keep detection separate from correlation, deduplication, and final reporting.

Analyzed Attributes
-------------------

- Secure
- HttpOnly
- SameSite
- Domain
- Path

Architecture
------------

HTTP Response Evidence
        |
        v
   Cookie Analyzer
        |
        v
Normalized Observations
        |
        v
 Finding Normalizer
        |
        v
Correlation / Risk Engine
        |
        v
      Report

Design Principles
-----------------

- The analyzer performs no network requests.
- The analyzer does not execute external tools.
- Cookie values are never included in normalized evidence.
- Missing attributes are observations and are not automatically treated as
  critical vulnerabilities.
- SameSite evaluation is context-sensitive and therefore conservative.
- Domain and Path attributes are retained as metadata for downstream analysis.
- One cookie can generate multiple independent security observations.
- The analyzer performs local deduplication only.
- Final correlation, deduplication, and risk classification remain outside
  this analyzer.

v1.4.0
"""

from __future__ import annotations

import re
from dataclasses import dataclass, field
from typing import Any, Iterable, Mapping


###############################################################################
# Constants
###############################################################################


ANALYZER_NAME = "cookies"

CATEGORY_INSECURE = "INSECURE_COOKIE"
CATEGORY_HTTPONLY = "MISSING_HTTPONLY"
CATEGORY_SECURE = "MISSING_SECURE"
CATEGORY_SAMESITE = "WEAK_SAMESITE"

DEFAULT_SEVERITY = "Medium"
DEFAULT_CONFIDENCE = "High"

DETECTION_METHOD = "Native HTTP Cookie Security Analysis"


###############################################################################
# Observation
###############################################################################


@dataclass(slots=True)
class CookieObservation:
    """
    Structured observation generated by the native cookie analyzer.
    """

    title: str

    description: str

    category: str

    target: str = ""

    host: str | None = None

    url: str | None = None

    cookie_name: str | None = None

    severity: str = DEFAULT_SEVERITY

    confidence: str = DEFAULT_CONFIDENCE

    source_tool: str = ANALYZER_NAME

    detection_method: str = DETECTION_METHOD

    evidence: dict[str, Any] = field(
        default_factory=dict
    )

    metadata: dict[str, Any] = field(
        default_factory=dict
    )

    cwe: str | None = None

    references: list[str] = field(
        default_factory=list
    )

    impact: str = ""

    remediation: str = ""

    def as_dict(
        self,
    ) -> dict[str, Any]:
        """
        Convert the observation into a mapping suitable for the universal
        finding-normalization layer.
        """

        metadata = dict(
            self.metadata
        )

        if self.cookie_name:
            metadata.setdefault(
                "cookie_name",
                self.cookie_name,
            )

        return {
            "title": self.title,
            "category": self.category,
            "target": self.target,
            "host": self.host,
            "url": self.url,
            "description": self.description,
            "severity": self.severity,
            "confidence": self.confidence,
            "evidence": dict(
                self.evidence
            ),
            "source_tool": self.source_tool,
            "detection_method": self.detection_method,
            "cwe": self.cwe,
            "references": list(
                self.references
            ),
            "impact": self.impact,
            "remediation": self.remediation,
            "metadata": metadata,
        }


###############################################################################
# Analyzer
###############################################################################


class CookieAnalyzer:
    """
    Analyze Set-Cookie response headers.

    The analyzer accepts raw Set-Cookie values, response mappings, or common
    HTTP response objects. It never performs network activity itself.
    """

    name = ANALYZER_NAME

    description = (
        "Analyze HTTP cookies for missing or weak security attributes."
    )

    ###########################################################################
    # Public API
    ###########################################################################

    def analyze(
        self,
        response: Any = None,
        *,
        target: str = "",
        set_cookie: Any = None,
        cookies: Any = None,
        headers: Mapping[str, Any] | None = None,
        **kwargs: Any,
    ) -> list[CookieObservation]:
        """
        Analyze cookies from an HTTP response.
        """

        effective_target = (
            target
            or self._extract_response_url(
                response
            )
            or ""
        )

        raw_values = self._collect_set_cookie_values(
            set_cookie=set_cookie,
            cookies=cookies,
            headers=headers,
            response=response,
        )

        if not raw_values:
            return []

        observations: list[CookieObservation] = []

        for raw_cookie in raw_values:

            parsed = self._parse_set_cookie(
                raw_cookie
            )

            if parsed is None:
                continue

            observations.extend(
                self._analyze_cookie(
                    parsed,
                    target=effective_target,
                )
            )

        return self._deduplicate(
            observations
        )

    ###########################################################################
    # Cookie analysis
    ###########################################################################

    def _analyze_cookie(
        self,
        cookie: Mapping[str, Any],
        *,
        target: str,
    ) -> list[CookieObservation]:
        """
        Analyze a single parsed Set-Cookie record.
        """

        name = cookie.get(
            "name"
        )

        if not name:
            return []

        secure = bool(
            cookie.get(
                "secure",
                False,
            )
        )

        httponly = bool(
            cookie.get(
                "httponly",
                False,
            )
        )

        samesite = cookie.get(
            "samesite"
        )

        domain = cookie.get(
            "domain"
        )

        path = cookie.get(
            "path"
        )

        observations: list[CookieObservation] = []

        is_https = self._is_https(
            target
        )

        #######################################################################
        # Secure
        #######################################################################

        if is_https and not secure:

            observations.append(
                self._build_observation(
                    category=CATEGORY_SECURE,
                    title=(
                        f"Missing Secure attribute on cookie '{name}'"
                    ),
                    description=(
                        f"The cookie '{name}' is set by an HTTPS target "
                        "without the Secure attribute."
                    ),
                    target=target,
                    cookie=cookie,
                    severity="Medium",
                    impact=(
                        "Without Secure, the browser may send the cookie over "
                        "an unencrypted HTTP connection if such a connection "
                        "is available, increasing exposure to interception."
                    ),
                    remediation=(
                        "Set the Secure attribute on cookies that should only "
                        "be transmitted over HTTPS."
                    ),
                    cwe="CWE-614",
                )
            )

        #######################################################################
        # HttpOnly
        #######################################################################

        if not httponly:

            observations.append(
                self._build_observation(
                    category=CATEGORY_HTTPONLY,
                    title=(
                        f"Missing HttpOnly attribute on cookie '{name}'"
                    ),
                    description=(
                        f"The cookie '{name}' does not define the HttpOnly "
                        "attribute."
                    ),
                    target=target,
                    cookie=cookie,
                    severity="Medium",
                    impact=(
                        "Client-side scripts may be able to access the cookie. "
                        "If an attacker can execute JavaScript in the "
                        "application context, the cookie may become accessible."
                    ),
                    remediation=(
                        "Set HttpOnly on authentication and other sensitive "
                        "cookies that do not require JavaScript access."
                    ),
                    cwe="CWE-1004",
                )
            )

        #######################################################################
        # SameSite
        #######################################################################

        if not samesite:

            observations.append(
                self._build_observation(
                    category=CATEGORY_SAMESITE,
                    title=(
                        f"Missing SameSite attribute on cookie '{name}'"
                    ),
                    description=(
                        f"The cookie '{name}' does not explicitly define "
                        "a SameSite policy."
                    ),
                    target=target,
                    cookie=cookie,
                    severity="Low",
                    impact=(
                        "The absence of an explicit SameSite policy can reduce "
                        "control over cross-site cookie transmission and may "
                        "increase exposure to cross-site request scenarios."
                    ),
                    remediation=(
                        "Set an explicit SameSite value appropriate for the "
                        "application. Prefer Strict or Lax where compatible "
                        "with application behavior; use None only when "
                        "cross-site cookie delivery is intentionally required."
                    ),
                    cwe="CWE-352",
                )
            )

        elif str(
            samesite
        ).lower() == "none":

            if not secure:

                observations.append(
                    self._build_observation(
                        category=CATEGORY_SAMESITE,
                        title=(
                            f"Insecure SameSite=None cookie '{name}'"
                        ),
                        description=(
                            f"The cookie '{name}' explicitly uses "
                            "SameSite=None without Secure."
                        ),
                        target=target,
                        cookie=cookie,
                        severity="Medium",
                        impact=(
                            "A cross-site cookie configured with SameSite=None "
                            "without Secure may not be accepted or may fail "
                            "to provide the intended security properties."
                        ),
                        remediation=(
                            "When SameSite=None is required, configure the "
                            "cookie with Secure and ensure cross-site delivery "
                            "is intentional."
                        ),
                        cwe="CWE-352",
                    )
                )

        #######################################################################
        # Domain
        #######################################################################

        if domain:

            normalized_domain = str(
                domain
            ).strip()

            if normalized_domain.startswith("."):

                observations.append(
                    self._build_observation(
                        category=CATEGORY_INSECURE,
                        title=(
                            f"Broad cookie Domain scope on '{name}'"
                        ),
                        description=(
                            f"The cookie '{name}' uses the broad Domain "
                            f"attribute '{normalized_domain}'."
                        ),
                        target=target,
                        cookie=cookie,
                        severity="Low",
                        impact=(
                            "A broadly scoped cookie may be sent to multiple "
                            "subdomains. If a less-trusted subdomain is "
                            "compromised, the cookie may become exposed."
                        ),
                        remediation=(
                            "Use the narrowest Domain scope required by the "
                            "application and avoid unnecessarily sharing "
                            "sensitive cookies across subdomains."
                        ),
                        cwe="CWE-565",
                    )
                )

        return observations

    ###########################################################################
    # Response extraction
    ###########################################################################

    @classmethod
    def _extract_response_url(
        cls,
        response: Any,
    ) -> str | None:
        """
        Extract a response URL from common response representations.
        """

        if response is None:
            return None

        if isinstance(
            response,
            Mapping,
        ):

            for key in (
                "url",
                "response_url",
                "final_url",
                "target",
            ):

                value = response.get(
                    key
                )

                if value:
                    return str(
                        value
                    ).strip()

            return None

        for attribute in (
            "url",
            "response_url",
            "final_url",
        ):

            value = getattr(
                response,
                attribute,
                None,
            )

            if value:
                return str(
                    value
                ).strip()

        return None

    @classmethod
    def _collect_set_cookie_values(
        cls,
        *,
        set_cookie: Any,
        cookies: Any,
        headers: Mapping[str, Any] | None,
        response: Any,
    ) -> list[Any]:
        """
        Collect Set-Cookie values from explicit arguments, headers, or a
        response-like object.
        """

        explicit = (
            set_cookie
            if set_cookie is not None
            else cookies
        )

        if explicit is not None:

            return cls._coerce_cookie_values(
                explicit
            )

        if headers is not None:

            values = cls._extract_header_value(
                headers,
                "set-cookie",
            )

            if values:
                return values

        if isinstance(
            response,
            Mapping,
        ):

            for key in (
                "headers",
                "response_headers",
                "http_headers",
            ):

                if key not in response:
                    continue

                values = cls._extract_header_value(
                    response.get(
                        key
                    ),
                    "set-cookie",
                )

                if values:
                    return values

            for key in (
                "set-cookie",
                "set_cookie",
                "cookies",
            ):

                if key in response:

                    values = cls._coerce_cookie_values(
                        response.get(
                            key
                        )
                    )

                    if values:
                        return values

            return []

        for attribute in (
            "headers",
            "response_headers",
        ):

            value = getattr(
                response,
                attribute,
                None,
            )

            if value is None:
                continue

            values = cls._extract_header_value(
                value,
                "set-cookie",
            )

            if values:
                return values

        for attribute in (
            "set_cookie",
            "set_cookie_header",
            "cookies",
        ):

            value = getattr(
                response,
                attribute,
                None,
            )

            if value is None:
                continue

            values = cls._coerce_cookie_values(
                value
            )

            if values:
                return values

        return []

    @staticmethod
    def _coerce_cookie_values(
        value: Any,
    ) -> list[Any]:
        """
        Convert common cookie input representations into a list.
        """

        if value is None:
            return []

        if isinstance(
            value,
            bytes,
        ):

            decoded = value.decode(
                "utf-8",
                errors="replace",
            )

            return [
                decoded
            ]

        if isinstance(
            value,
            str,
        ):

            return [
                value
            ]

        if isinstance(
            value,
            Mapping,
        ):

            return [
                value
            ]

        if isinstance(
            value,
            Iterable,
        ):

            return [
                item
                for item in value
                if item is not None
            ]

        return [
            value
        ]

    @classmethod
    def _extract_header_value(
        cls,
        headers: Any,
        name: str,
    ) -> list[Any]:
        """
        Extract a case-insensitive header value.

        Header collections represented by mappings, sequences of pairs, or
        response-header objects are supported.
        """

        normalized_name = str(
            name
        ).strip().lower()

        if headers is None:
            return []

        if isinstance(
            headers,
            Mapping,
        ):

            for key, value in headers.items():

                if str(
                    key
                ).strip().lower() != normalized_name:
                    continue

                return cls._coerce_cookie_values(
                    value
                )

            return []

        if isinstance(
            headers,
            str,
        ):

            values: list[str] = []

            for line in headers.splitlines():

                if ":" not in line:
                    continue

                key, value = line.split(
                    ":",
                    1,
                )

                if key.strip().lower() != normalized_name:
                    continue

                value = value.strip()

                if value:
                    values.append(
                        value
                    )

            return values

        if isinstance(
            headers,
            Iterable,
        ):

            values: list[Any] = []

            for item in headers:

                if not isinstance(
                    item,
                    (list, tuple),
                ):
                    continue

                if len(item) < 2:
                    continue

                key = str(
                    item[0]
                ).strip().lower()

                if key != normalized_name:
                    continue

                values.extend(
                    cls._coerce_cookie_values(
                        item[1]
                    )
                )

            return values

        return []

    ###########################################################################
    # Set-Cookie parsing
    ###########################################################################

    @classmethod
    def _parse_set_cookie(
        cls,
        raw_cookie: Any,
    ) -> dict[str, Any] | None:
        """
        Parse one Set-Cookie value without retaining the cookie value.

        Only the cookie name and security-relevant attributes are preserved.
        """

        if isinstance(
            raw_cookie,
            Mapping,
        ):

            name = (
                raw_cookie.get("name")
                or raw_cookie.get("cookie_name")
            )

            if not name:
                return None

            return {
                "name": str(
                    name
                ).strip(),
                "secure": bool(
                    raw_cookie.get(
                        "secure",
                        False,
                    )
                ),
                "httponly": bool(
                    raw_cookie.get(
                        "httponly",
                        raw_cookie.get(
                            "http_only",
                            False,
                        ),
                    )
                ),
                "samesite": (
                    str(
                        raw_cookie.get(
                            "samesite",
                            raw_cookie.get(
                                "same_site",
                                "",
                            ),
                        )
                    ).strip()
                    or None
                ),
                "domain": (
                    str(
                        raw_cookie.get(
                            "domain",
                            "",
                        )
                    ).strip()
                    or None
                ),
                "path": (
                    str(
                        raw_cookie.get(
                            "path",
                            "",
                        )
                    ).strip()
                    or None
                ),
            }

        if isinstance(
            raw_cookie,
            bytes,
        ):

            raw_cookie = raw_cookie.decode(
                "utf-8",
                errors="replace",
            )

        value = str(
            raw_cookie
        ).strip()

        if not value:
            return None

        parts = [
            part.strip()
            for part in value.split(";")
            if part.strip()
        ]

        if not parts:
            return None

        first = parts[0]

        if "=" not in first:
            return None

        name, _cookie_value = first.split(
            "=",
            1,
        )

        name = name.strip()

        if not cls._valid_cookie_name(
            name
        ):
            return None

        parsed: dict[str, Any] = {
            "name": name,
            "secure": False,
            "httponly": False,
            "samesite": None,
            "domain": None,
            "path": None,
        }

        for attribute in parts[1:]:

            if "=" in attribute:

                key, attribute_value = attribute.split(
                    "=",
                    1,
                )

                key = key.strip().lower()
                attribute_value = attribute_value.strip()

                if key == "domain":
                    parsed[
                        "domain"
                    ] = attribute_value

                elif key == "path":
                    parsed[
                        "path"
                    ] = attribute_value

                elif key == "samesite":
                    parsed[
                        "samesite"
                    ] = attribute_value

                continue

            key = attribute.strip().lower()

            if key == "secure":
                parsed[
                    "secure"
                ] = True

            elif key == "httponly":
                parsed[
                    "httponly"
                ] = True

        return parsed

    @staticmethod
    def _valid_cookie_name(
        value: str,
    ) -> bool:
        """
        Validate a cookie name conservatively.
        """

        if not value:
            return False

        return re.fullmatch(
            r"[!#$%&'*+\-.^_`|~0-9A-Za-z]+",
            value,
        ) is not None

    ###########################################################################
    # Observation construction
    ###########################################################################

    @classmethod
    def _build_observation(
        cls,
        *,
        category: str,
        title: str,
        description: str,
        target: str,
        cookie: Mapping[str, Any],
        severity: str,
        impact: str,
        remediation: str,
        cwe: str | None = None,
    ) -> CookieObservation:
        """
        Construct a cookie-security observation while excluding the cookie
        value itself from normalized evidence.
        """

        cookie_name = str(
            cookie.get(
                "name",
                "",
            )
        ).strip()

        evidence: dict[str, Any] = {
            "cookie_name": cookie_name,
            "secure": bool(
                cookie.get(
                    "secure",
                    False,
                )
            ),
            "httponly": bool(
                cookie.get(
                    "httponly",
                    False,
                )
            ),
            "samesite": cookie.get(
                "samesite"
            ),
        }

        if cookie.get(
            "domain"
        ) is not None:

            evidence[
                "domain"
            ] = str(
                cookie.get(
                    "domain"
                )
            )

        if cookie.get(
            "path"
        ) is not None:

            evidence[
                "path"
            ] = str(
                cookie.get(
                    "path"
                )
            )

        host = cls._extract_host(
            target
        )

        url = (
            target
            if cls._is_url(
                target
            )
            else None
        )

        metadata = {
            "analyzer": ANALYZER_NAME,
            "issue": category,
        }

        return CookieObservation(
            title=title,
            description=description,
            category=category,
            target=target,
            host=host,
            url=url,
            cookie_name=cookie_name,
            severity=severity,
            confidence=DEFAULT_CONFIDENCE,
            source_tool=ANALYZER_NAME,
            detection_method=DETECTION_METHOD,
            evidence=evidence,
            metadata=metadata,
            cwe=cwe,
            impact=impact,
            remediation=remediation,
        )

    ###########################################################################
    # Target helpers
    ###########################################################################

    @staticmethod
    def _is_url(
        value: Any,
    ) -> bool:
        """
        Return whether a target appears to be an HTTP(S) URL.
        """

        if not value:
            return False

        normalized = str(
            value
        ).strip().lower()

        return (
            normalized.startswith(
                "http://"
            )
            or normalized.startswith(
                "https://"
            )
        )

    @classmethod
    def _is_https(
        cls,
        target: Any,
    ) -> bool:
        """
        Return whether a target uses HTTPS.
        """

        if not target:
            return False

        return str(
            target
        ).strip().lower().startswith(
            "https://"
        )

    @classmethod
    def _extract_host(
        cls,
        target: Any,
    ) -> str | None:
        """
        Extract a hostname from an HTTP(S) target.
        """

        if not cls._is_url(
            target
        ):
            return None

        value = str(
            target
        ).strip()

        authority = value.split(
            "://",
            1,
        )[1]

        authority = authority.split(
            "/",
            1,
        )[0]

        authority = authority.split(
            "?",
            1,
        )[0]

        authority = authority.split(
            "#",
            1,
        )[0]

        if "@" in authority:

            authority = authority.rsplit(
                "@",
                1,
            )[1]

        if authority.startswith(
            "["
        ):

            closing = authority.find(
                "]"
            )

            if closing != -1:

                return authority[
                    1:closing
                ]

        return (
            authority.rsplit(
                ":",
                1,
            )[0]
            if ":" in authority
            else authority
        ) or None

    ###########################################################################
    # Deduplication
    ###########################################################################

    @staticmethod
    def _deduplicate(
        observations: list[CookieObservation],
    ) -> list[CookieObservation]:
        """
        Remove duplicate observations generated from the same cookie
        configuration.
        """

        unique: list[
            CookieObservation
        ] = []

        seen: set[
            tuple[Any, ...]
        ] = set()

        for observation in observations:

            evidence = observation.evidence

            fingerprint = (
                observation.category,
                observation.target,
                observation.cookie_name,
                evidence.get(
                    "secure"
                ),
                evidence.get(
                    "httponly"
                ),
                evidence.get(
                    "samesite"
                ),
                evidence.get(
                    "domain"
                ),
                evidence.get(
                    "path"
                ),
            )

            if fingerprint in seen:
                continue

            seen.add(
                fingerprint
            )

            unique.append(
                observation
            )

        return unique


###############################################################################
# Compatibility Names
###############################################################################


# CookieAnalyzer is the canonical implementation. These aliases preserve the
# names consumed by scopeforgex.analyzers and NativeAnalyzerEngine without
# introducing duplicate analyzer implementations.
CookiesAnalyzer = CookieAnalyzer

CookieSecurityAnalyzer = CookieAnalyzer

Analyzer = CookieAnalyzer


###############################################################################
# Public API
###############################################################################


INSECURE_COOKIE = CATEGORY_INSECURE

MISSING_HTTPONLY = CATEGORY_HTTPONLY

MISSING_SECURE = CATEGORY_SECURE

WEAK_SAMESITE = CATEGORY_SAMESITE


__all__ = [
    "CookieObservation",
    "CookieAnalyzer",
    "CookiesAnalyzer",
    "CookieSecurityAnalyzer",
    "INSECURE_COOKIE",
    "MISSING_HTTPONLY",
    "MISSING_SECURE",
    "WEAK_SAMESITE",
]
