"""
ScopeForgeX HTTP Methods Analyzer
=================================

Native analyzer for evaluating HTTP methods exposed by an HTTP service.

The analyzer consumes normalized HTTP response/request evidence collected by
ScopeForgeX. It does not execute HTTP requests and does not construct tool
commands.

Responsibilities
----------------

- Inspect HTTP methods reported by upstream collectors.
- Identify potentially unnecessary or risky methods.
- Produce structured observations for the universal Finding pipeline.
- Preserve the original method evidence.
- Distinguish informational method exposure from potentially security-
  relevant configurations.
- Avoid treating every non-GET/POST method as a vulnerability.

Architecture
------------

HTTP Service Evidence
        |
        v
HTTP Methods Analyzer
        |
        +--> Method Observations
        |
        +--> Security Findings
                    |
                    v
             Finding Normalizer
                    |
                    v
             Correlation Engine
                    |
                    v
                  Report

Design Principles
-----------------

- Analyzer only; no network execution.
- OPTIONS alone is not considered a vulnerability.
- TRACE is security-relevant because it may enable HTTP Trace attacks,
  but exposure alone does not prove exploitability.
- PUT/DELETE/PATCH are not automatically vulnerabilities because legitimate
  REST APIs may require them.
- CONNECT is treated as potentially dangerous when exposed by a web service.
- Evidence and confidence remain separate from final risk classification.
- The universal Finding model remains the canonical downstream structure.

v1.1.0
"""

from __future__ import annotations

from dataclasses import dataclass, field
from typing import Any, Iterable, Mapping


###############################################################################
# Constants
###############################################################################


ANALYZER_NAME = "http_methods"

CATEGORY = "HTTP Method Misconfiguration"

DETECTION_METHOD = "ScopeForgeX HTTP Methods Analyzer"

DEFAULT_CONFIDENCE = "Medium"

# Methods which may deserve security review when unexpectedly exposed.
REVIEW_METHODS = frozenset(
    {
        "TRACE",
        "CONNECT",
        "PUT",
        "DELETE",
        "PATCH",
    }
)

# OPTIONS is commonly exposed for legitimate capability discovery and CORS.
INFORMATIONAL_METHODS = frozenset(
    {
        "OPTIONS",
        "HEAD",
    }
)

# Methods that are normally expected on HTTP services.
COMMON_METHODS = frozenset(
    {
        "GET",
        "POST",
        "HEAD",
        "OPTIONS",
    }
)


###############################################################################
# Observation
###############################################################################


@dataclass(slots=True)
class HTTPMethodObservation:
    """
    Structured observation generated by the HTTP methods analyzer.

    This is intentionally compatible with the universal Finding conversion
    layer while remaining independent from the final Finding implementation.
    """

    title: str

    description: str

    target: str = ""

    host: str | None = None

    port: int | None = None

    url: str | None = None

    method: str | None = None

    severity: str = "Informational"

    confidence: str = DEFAULT_CONFIDENCE

    source_tool: str = ANALYZER_NAME

    detection_method: str = DETECTION_METHOD

    evidence: dict[str, Any] = field(
        default_factory=dict
    )

    metadata: dict[str, Any] = field(
        default_factory=dict
    )

    def as_dict(
        self,
    ) -> dict[str, Any]:
        """
        Serialize the observation into a normalized finding-compatible map.
        """

        metadata = dict(
            self.metadata
        )

        if self.method:
            metadata.setdefault(
                "method",
                self.method,
            )

        return {
            "title": self.title,
            "category": CATEGORY,
            "description": self.description,
            "target": self.target,
            "host": self.host,
            "port": self.port,
            "url": self.url,
            "parameter": None,
            "severity": self.severity,
            "confidence": self.confidence,
            "evidence": self.evidence,
            "source_tool": self.source_tool,
            "detection_method": self.detection_method,
            "cwe": "CWE-749"
            if self.method == "TRACE"
            else None,
            "cve": None,
            "references": [],
            "impact": self._impact(),
            "remediation": self._remediation(),
            "metadata": metadata,
        }

    def _impact(
        self,
    ) -> str:
        """Return method-specific impact guidance."""

        if self.method == "TRACE":
            return (
                "An unnecessarily enabled TRACE method may increase exposure "
                "to HTTP Trace-based attacks and can disclose request "
                "headers in environments where TRACE is not required."
            )

        if self.method == "CONNECT":
            return (
                "Unexpected CONNECT support on a web service may provide "
                "proxy or tunneling functionality that should be restricted "
                "to intended infrastructure."
            )

        if self.method in {
            "PUT",
            "DELETE",
            "PATCH",
        }:
            return (
                f"The {self.method} method may permit state-changing "
                "operations. Security impact depends on authentication, "
                "authorization and application behavior."
            )

        return (
            "The exposed HTTP method should be reviewed against the "
            "application's intended functionality."
        )

    def _remediation(
        self,
    ) -> str:
        """Return method-specific remediation guidance."""

        if self.method == "TRACE":
            return (
                "Disable TRACE unless it is explicitly required. Restrict "
                "HTTP methods at the web-server, reverse-proxy or application "
                "layer."
            )

        if self.method == "CONNECT":
            return (
                "Disable or restrict CONNECT on application-facing web "
                "services unless proxy or tunneling functionality is "
                "explicitly required."
            )

        if self.method in {
            "PUT",
            "DELETE",
            "PATCH",
        }:
            return (
                f"Verify that {self.method} is required. Enforce strong "
                "authentication and authorization for the operation and "
                "disable the method where it is not needed."
            )

        return (
            "Allow only HTTP methods required by the application and "
            "document the intended method policy."
        )


###############################################################################
# Analyzer
###############################################################################


class HTTPMethodsAnalyzer:
    """
    Analyze HTTP method evidence without performing network requests.

    Supported input forms include:

    - Mapping containing ``methods``.
    - Mapping containing ``allow`` / ``allowed_methods``.
    - An HTTP ``Allow`` header value.
    - A sequence of method names.
    - A response-like mapping containing headers.

    Example
    -------

    analyzer = HTTPMethodsAnalyzer()

    observations = analyzer.analyze(
        {
            "target": "https://example.com",
            "methods": ["GET", "POST", "TRACE"],
        }
    )
    """

    name = ANALYZER_NAME

    category = CATEGORY

    ###########################################################################
    # Public API
    ###########################################################################

    def analyze(
        self,
        evidence: Any,
        *,
        target: str = "",
        host: str | None = None,
        port: int | None = None,
        url: str | None = None,
        **kwargs: Any,
    ) -> list[HTTPMethodObservation]:
        """
        Analyze supplied HTTP method evidence.

        No network requests are made by this method.
        """

        context = self._normalize_input(
            evidence
        )

        effective_target = (
            _text(
                context.get(
                    "target"
                )
            )
            or target
        )

        effective_host = (
            _text(
                context.get(
                    "host"
                )
            )
            or host
        )

        effective_port = (
            _safe_int(
                context.get(
                    "port"
                )
            )
            if context.get(
                "port"
            ) is not None
            else port
        )

        effective_url = (
            _text(
                context.get(
                    "url"
                )
            )
            or url
            or (
                effective_target
                if _is_http_url(
                    effective_target
                )
                else None
            )
        )

        methods = self._extract_methods(
            context
        )

        if not methods:
            return []

        observations: list[
            HTTPMethodObservation
        ] = []

        for method in methods:

            if method in INFORMATIONAL_METHODS:
                continue

            if method not in REVIEW_METHODS:
                continue

            observations.append(
                self._build_observation(
                    method=method,
                    target=effective_target,
                    host=effective_host,
                    port=effective_port,
                    url=effective_url,
                    context=context,
                )
            )

        return self._deduplicate(
            observations
        )

    ###########################################################################
    # Input normalization
    ###########################################################################

    @classmethod
    def _normalize_input(
        cls,
        evidence: Any,
    ) -> dict[str, Any]:
        """
        Normalize common HTTP evidence representations.
        """

        if evidence is None:
            return {}

        if isinstance(
            evidence,
            Mapping,
        ):

            context = dict(
                evidence
            )

            headers = context.get(
                "headers"
            )

            if isinstance(
                headers,
                Mapping,
            ):

                normalized_headers = {
                    str(
                        key
                    ).lower(): value
                    for key, value in headers.items()
                }

                if "allow" not in context:

                    allow = normalized_headers.get(
                        "allow"
                    )

                    if allow:
                        context[
                            "allow"
                        ] = allow

            return context

        if isinstance(
            evidence,
            str,
        ):

            return {
                "allow": evidence,
            }

        if isinstance(
            evidence,
            Iterable,
        ):

            return {
                "methods": list(
                    evidence
                ),
            }

        return {}

    ###########################################################################
    # Method extraction
    ###########################################################################

    @classmethod
    def _extract_methods(
        cls,
        context: Mapping[str, Any],
    ) -> list[str]:
        """
        Extract and normalize HTTP methods from the supplied evidence.
        """

        candidates: list[Any] = []

        for key in (
            "methods",
            "allowed_methods",
            "allow",
            "http_methods",
        ):

            value = context.get(
                key
            )

            if value is None:
                continue

            if isinstance(
                value,
                str,
            ):

                candidates.extend(
                    value.replace(
                        ",",
                        " ",
                    ).split()
                )

            elif isinstance(
                value,
                Iterable,
            ):

                candidates.extend(
                    value
                )

            else:

                candidates.append(
                    value
                )

        normalized: list[str] = []

        seen: set[str] = set()

        for value in candidates:

            method = _text(
                value
            ).upper()

            if not method:
                continue

            # Ignore punctuation commonly found around Allow header values.
            method = method.strip(
                " ,;"
            )

            if not method:
                continue

            if method in seen:
                continue

            seen.add(
                method
            )

            normalized.append(
                method
            )

        return normalized

    ###########################################################################
    # Observation construction
    ###########################################################################

    @staticmethod
    def _build_observation(
        *,
        method: str,
        target: str,
        host: str | None,
        port: int | None,
        url: str | None,
        context: Mapping[str, Any],
    ) -> HTTPMethodObservation:
        """
        Build a normalized observation for a review-worthy HTTP method.
        """

        if method == "TRACE":

            title = "HTTP TRACE Method Enabled"

            severity = "Medium"

            description = (
                "The HTTP TRACE method is exposed by the target. TRACE is "
                "normally unnecessary for application-facing services and "
                "should be disabled unless explicitly required."
            )

        elif method == "CONNECT":

            title = "HTTP CONNECT Method Exposed"

            severity = "Medium"

            description = (
                "The HTTP CONNECT method is exposed by the target. CONNECT "
                "can provide proxy or tunneling functionality and should be "
                "restricted when not explicitly required."
            )

        else:

            title = (
                f"HTTP {method} Method Exposed"
            )

            severity = "Low"

            description = (
                f"The HTTP {method} method is exposed by the target. "
                "This is not inherently a vulnerability, but the method "
                "should be reviewed to ensure that authorization and "
                "application controls are correctly enforced."
            )

        return HTTPMethodObservation(
            title=title,
            description=description,
            target=target,
            host=host,
            port=port,
            url=url,
            method=method,
            severity=severity,
            confidence=DEFAULT_CONFIDENCE,
            evidence={
                "method": method,
                "methods": list(
                    HTTPMethodsAnalyzer._extract_methods(
                        context
                    )
                ),
                "allow_header": context.get(
                    "allow"
                ),
                "raw": context.get(
                    "raw"
                ),
            },
            metadata={
                "analyzer": ANALYZER_NAME,
                "review_required": True,
                "method_category": (
                    "trace"
                    if method == "TRACE"
                    else (
                        "proxy_or_tunneling"
                        if method == "CONNECT"
                        else "state_changing"
                    )
                ),
            },
        )

    ###########################################################################
    # Deduplication
    ###########################################################################

    @staticmethod
    def _deduplicate(
        observations: list[HTTPMethodObservation],
    ) -> list[HTTPMethodObservation]:
        """Remove duplicate method observations."""

        unique: list[
            HTTPMethodObservation
        ] = []

        seen: set[
            tuple[str, str, str]
        ] = set()

        for observation in observations:

            fingerprint = (
                observation.target,
                observation.url or "",
                observation.method or "",
            )

            if fingerprint in seen:
                continue

            seen.add(
                fingerprint
            )

            unique.append(
                observation
            )

        return unique


###############################################################################
# Helpers
###############################################################################


def _text(
    value: Any,
) -> str:
    """Return normalized text."""

    if value is None:
        return ""

    return str(
        value
    ).strip()


def _safe_int(
    value: Any,
) -> int | None:
    """Convert a value to an integer when possible."""

    if value is None:
        return None

    try:

        return int(
            value
        )

    except (
        TypeError,
        ValueError,
    ):

        return None


def _is_http_url(
    value: str,
) -> bool:
    """Return True when the supplied value is an HTTP(S) URL."""

    normalized = _text(
        value
    ).lower()

    return (
        normalized.startswith(
            "http://"
        )
        or normalized.startswith(
            "https://"
        )
    )


###############################################################################
# Compatibility aliases
###############################################################################


# HTTPMethodsAnalyzer is the canonical implementation. Preserve the historical
# package-level constant expected by ScopeForgeX native analyzer consumers.
Analyzer = HTTPMethodsAnalyzer

HTTP_METHOD_MISCONFIGURATION = CATEGORY


###############################################################################
# Public API
###############################################################################


__all__ = [
    "HTTPMethodsAnalyzer",
    "HTTPMethodObservation",
    "Analyzer",
    "ANALYZER_NAME",
    "CATEGORY",
    "HTTP_METHOD_MISCONFIGURATION",
    "DETECTION_METHOD",
    "DEFAULT_CONFIDENCE",
    "REVIEW_METHODS",
    "INFORMATIONAL_METHODS",
    "COMMON_METHODS",
]
