"""
ScopeForgeX Sensitive Files Analyzer
=====================================

Native analyzer for identifying potentially sensitive files and resources
from previously collected HTTP/web evidence.

The analyzer does not perform network requests. It evaluates URLs, paths,
HTTP metadata, and response evidence supplied by ScopeForgeX collectors.

Responsibilities
----------------

- Identify potentially sensitive files and resources.
- Recognize common configuration, source-control, backup, debug, and
  source-map exposures.
- Identify directory-listing indicators.
- Preserve the original resource evidence.
- Produce normalized observations for the universal Finding pipeline.
- Avoid treating every unusual filename as a vulnerability.
- Keep detection independent from HTTP execution and command construction.

Architecture
------------

HTTP / Web Enumeration
        |
        v
Sensitive Files Analyzer
        |
        +--> Resource Observations
        |
        +--> Security Findings
                    |
                    v
             Finding Normalizer
                    |
                    v
             Correlation Engine
                    |
                    v
                  Report

Design Principles
-----------------

- Analyzer only; no network execution.
- Discovery of a potentially sensitive path is not automatically proof
  that sensitive contents are exposed.
- Confidence reflects the evidence supplied to the analyzer.
- Exact response status and content indicators are preserved when present.
- Secrets are not extracted or displayed by this analyzer.
- Directory listing detection is based on explicit evidence rather than
  assumptions from a directory-looking URL.
- The universal Finding model remains the canonical downstream structure.

v1.0.0
"""

from __future__ import annotations

import re
from dataclasses import dataclass, field
from typing import Any, Iterable, Mapping
from urllib.parse import urlsplit


###############################################################################
# Constants
###############################################################################


ANALYZER_NAME = "sensitive_files"

CATEGORY = "Sensitive File Exposure"

DETECTION_METHOD = "ScopeForgeX Sensitive File Analyzer"

DEFAULT_CONFIDENCE = "Medium"


# Exact filenames or path components commonly associated with sensitive
# configuration or deployment information.
SENSITIVE_FILENAMES = frozenset(
    {
        ".env",
        ".env.local",
        ".env.production",
        ".env.development",
        ".git/config",
        ".git/HEAD",
        ".git/index",
        ".git/packed-refs",
        ".svn/entries",
        ".hg/store",
        "web.config",
        "appsettings.json",
        "appsettings.production.json",
        "phpinfo.php",
        "server-status",
        "server-info",
        "crossdomain.xml",
        "clientaccesspolicy.xml",
    }
)


# Backup/source/archive extensions which may expose application material.
BACKUP_EXTENSIONS = (
    ".bak",
    ".backup",
    ".old",
    ".orig",
    ".save",
    ".swp",
    ".swo",
    ".tmp",
    ".temp",
    ".zip",
    ".tar",
    ".tar.gz",
    ".tgz",
    ".gz",
    ".7z",
    ".rar",
)


# Source and configuration extensions that deserve review when directly
# exposed by a production web server.
SOURCE_EXTENSIONS = (
    ".sql",
    ".sqlite",
    ".sqlite3",
    ".db",
    ".conf",
    ".config",
    ".ini",
    ".yaml",
    ".yml",
    ".toml",
)


# Common debug/development paths.
DEBUG_PATHS = (
    "/debug",
    "/debug/",
    "/phpinfo.php",
    "/server-status",
    "/server-info",
    "/actuator",
    "/actuator/",
    "/metrics",
    "/health",
)


# Common directory-listing indicators.
DIRECTORY_LISTING_MARKERS = (
    "index of /",
    "directory listing for",
    "parent directory",
)


###############################################################################
# Observation
###############################################################################


@dataclass(slots=True)
class SensitiveFileObservation:
    """
    Structured observation generated by the sensitive-file analyzer.
    """

    title: str

    description: str

    target: str = ""

    host: str | None = None

    port: int | None = None

    url: str | None = None

    path: str | None = None

    resource_type: str | None = None

    severity: str = "Medium"

    confidence: str = DEFAULT_CONFIDENCE

    source_tool: str = ANALYZER_NAME

    detection_method: str = DETECTION_METHOD

    evidence: dict[str, Any] = field(
        default_factory=dict
    )

    metadata: dict[str, Any] = field(
        default_factory=dict
    )

    def as_dict(self) -> dict[str, Any]:
        """
        Serialize the observation into a Finding-compatible mapping.
        """

        metadata = dict(
            self.metadata
        )

        if self.path:
            metadata.setdefault(
                "path",
                self.path,
            )

        if self.resource_type:
            metadata.setdefault(
                "resource_type",
                self.resource_type,
            )

        return {
            "title": self.title,
            "category": CATEGORY,
            "description": self.description,
            "target": self.target,
            "host": self.host,
            "port": self.port,
            "url": self.url,
            "parameter": None,
            "severity": self.severity,
            "confidence": self.confidence,
            "evidence": self.evidence,
            "source_tool": self.source_tool,
            "detection_method": self.detection_method,
            "cwe": "CWE-538",
            "cve": None,
            "references": [],
            "impact": self._impact(),
            "remediation": self._remediation(),
            "metadata": metadata,
        }

    def _impact(self) -> str:
        """Return generic impact guidance for the observation."""

        if self.resource_type == "directory_listing":
            return (
                "Directory listing may disclose application structure, "
                "filenames, backups, internal resources, and other "
                "information useful for further attack."
            )

        if self.resource_type == "source_control":
            return (
                "Exposed source-control metadata may disclose source code, "
                "repository history, configuration, or credentials and may "
                "enable reconstruction of application internals."
            )

        if self.resource_type == "configuration":
            return (
                "Exposed configuration resources may disclose application "
                "settings, internal paths, service configuration, or "
                "credentials."
            )

        if self.resource_type == "backup":
            return (
                "Exposed backup or archive material may contain source code, "
                "configuration, database contents, credentials, or other "
                "sensitive application data."
            )

        if self.resource_type == "debug":
            return (
                "Exposed debug or diagnostic functionality may disclose "
                "implementation details, environment information, internal "
                "paths, or sensitive application data."
            )

        return (
            "The exposed resource may disclose information that should not "
            "be directly accessible through the public web service."
        )

    def _remediation(self) -> str:
        """Return remediation guidance."""

        if self.resource_type == "directory_listing":
            return (
                "Disable directory indexing/listing on the affected web "
                "server and ensure sensitive resources cannot be directly "
                "requested."
            )

        if self.resource_type == "source_control":
            return (
                "Remove source-control metadata from the web root and block "
                "direct access to repository directories and files."
            )

        if self.resource_type == "backup":
            return (
                "Remove backup and archive files from publicly served "
                "directories. Store backups outside the web root and restrict "
                "access to deployment artifacts."
            )

        if self.resource_type == "debug":
            return (
                "Disable unnecessary debugging and diagnostic endpoints in "
                "production and restrict administrative diagnostics."
            )

        if self.resource_type == "configuration":
            return (
                "Remove sensitive configuration files from publicly served "
                "directories and enforce server-side access controls."
            )

        return (
            "Remove the sensitive resource from the public web root or "
            "restrict access to authorized users only."
        )


###############################################################################
# Analyzer
###############################################################################


class SensitiveFilesAnalyzer:
    """
    Analyze previously collected web-resource evidence.

    The analyzer accepts common collector representations, including:

    - A URL string.
    - A mapping containing ``url`` or ``path``.
    - A mapping containing HTTP status and response body.
    - A sequence of URLs/resources.

    It never requests the supplied URL.
    """

    name = ANALYZER_NAME

    category = CATEGORY

    ###########################################################################
    # Public API
    ###########################################################################

    def analyze(
        self,
        evidence: Any,
        *,
        target: str = "",
        host: str | None = None,
        port: int | None = None,
        **kwargs: Any,
    ) -> list[SensitiveFileObservation]:
        """
        Analyze supplied resource evidence.

        No network requests are made.
        """

        resources = self._normalize_resources(
            evidence
        )

        observations: list[SensitiveFileObservation] = []

        for resource in resources:

            observation = self._analyze_resource(
                resource,
                target=target,
                host=host,
                port=port,
            )

            if observation is not None:
                observations.append(
                    observation
                )

        return self._deduplicate(
            observations
        )

    ###########################################################################
    # Resource normalization
    ###########################################################################

    @classmethod
    def _normalize_resources(
        cls,
        evidence: Any,
    ) -> list[dict[str, Any]]:
        """
        Normalize supported evidence representations.
        """

        if evidence is None:
            return []

        if isinstance(
            evidence,
            str,
        ):
            return [
                {
                    "url": evidence,
                }
            ]

        if isinstance(
            evidence,
            Mapping,
        ):
            # A mapping representing one resource.
            if any(
                key in evidence
                for key in (
                    "url",
                    "path",
                    "resource",
                    "status_code",
                    "status",
                    "body",
                    "response",
                )
            ):
                return [
                    dict(
                        evidence
                    )
                ]

            # A mapping of URL -> metadata.
            resources: list[dict[str, Any]] = []

            for key, value in evidence.items():

                if isinstance(
                    value,
                    Mapping,
                ):
                    item = dict(
                        value
                    )
                    item.setdefault(
                        "url",
                        str(
                            key
                        ),
                    )
                    resources.append(
                        item
                    )
                else:
                    resources.append(
                        {
                            "url": str(
                                key
                            ),
                            "value": value,
                        }
                    )

            return resources

        if isinstance(
            evidence,
            Iterable,
        ):
            resources = []

            for item in evidence:

                if isinstance(
                    item,
                    Mapping,
                ):
                    resources.append(
                        dict(
                            item
                        )
                    )
                else:
                    resources.append(
                        {
                            "url": str(
                                item
                            ),
                        }
                    )

            return resources

        return []

    ###########################################################################
    # Resource analysis
    ###########################################################################

    @classmethod
    def _analyze_resource(
        cls,
        resource: Mapping[str, Any],
        *,
        target: str,
        host: str | None,
        port: int | None,
    ) -> SensitiveFileObservation | None:
        """
        Analyze a single resource.
        """

        url = (
            _text(
                resource.get("url")
            )
            or _text(
                resource.get("resource")
            )
        )

        path = (
            _text(
                resource.get("path")
            )
        )

        if not path and url:
            path = cls._extract_path(
                url
            )

        if not path:
            return cls._analyze_body(
                resource,
                target=target,
                host=host,
                port=port,
                url=url or None,
            )

        normalized_path = cls._normalize_path(
            path
        )

        classification = cls._classify_path(
            normalized_path
        )

        status_code = cls._status_code(
            resource
        )

        body = cls._response_body(
            resource
        )

        listing = cls._is_directory_listing(
            body
        )

        if listing:
            classification = (
                "directory_listing"
            )

        if classification is None:
            return None

        severity, confidence = cls._severity_confidence(
            classification=classification,
            status_code=status_code,
            body=body,
            resource=resource,
        )

        effective_host = (
            _text(
                resource.get("host")
            )
            or host
        )

        effective_port = (
            _safe_int(
                resource.get("port")
            )
            if resource.get("port") is not None
            else port
        )

        effective_target = (
            target
            or url
            or effective_host
            or ""
        )

        title = cls._title(
            classification,
            normalized_path,
        )

        description = cls._description(
            classification=classification,
            path=normalized_path,
            status_code=status_code,
        )

        return SensitiveFileObservation(
            title=title,
            description=description,
            target=effective_target,
            host=effective_host,
            port=effective_port,
            url=url or None,
            path=normalized_path,
            resource_type=classification,
            severity=severity,
            confidence=confidence,
            evidence={
                "path": normalized_path,
                "url": url or None,
                "status_code": status_code,
                "content_type": cls._content_type(
                    resource
                ),
                "listing_detected": listing,
                "response_evidence": cls._safe_body_preview(
                    body
                ),
                "raw": resource.get(
                    "raw"
                ),
            },
            metadata={
                "analyzer": ANALYZER_NAME,
                "classification": classification,
            },
        )

    ###########################################################################
    # Body-only analysis
    ###########################################################################

    @classmethod
    def _analyze_body(
        cls,
        resource: Mapping[str, Any],
        *,
        target: str,
        host: str | None,
        port: int | None,
        url: str | None,
    ) -> SensitiveFileObservation | None:
        """Detect directory listings from response content."""

        body = cls._response_body(
            resource
        )

        if not cls._is_directory_listing(
            body
        ):
            return None

        path = (
            cls._extract_path(
                url
            )
            if url
            else None
        )

        return SensitiveFileObservation(
            title="Directory Listing Exposed",
            description=(
                "The supplied HTTP response contains explicit indicators "
                "of directory listing/index exposure."
            ),
            target=(
                target
                or url
                or host
                or ""
            ),
            host=host,
            port=port,
            url=url,
            path=path,
            resource_type="directory_listing",
            severity="Low",
            confidence="High",
            evidence={
                "url": url,
                "status_code": cls._status_code(
                    resource
                ),
                "listing_detected": True,
                "response_evidence": cls._safe_body_preview(
                    body
                ),
            },
            metadata={
                "analyzer": ANALYZER_NAME,
                "classification": "directory_listing",
            },
        )

    ###########################################################################
    # Classification
    ###########################################################################

    @staticmethod
    def _classify_path(
        path: str,
    ) -> str | None:
        """
        Classify a path according to the type of potentially sensitive
        resource it represents.
        """

        lowered = path.lower()

        # Source-control metadata gets priority over generic extensions.
        for marker in (
            "/.git/",
            "/.git",
            "/.svn/",
            "/.svn",
            "/.hg/",
            "/.hg",
        ):
            if marker in lowered:
                return "source_control"

        filename = lowered.rsplit(
            "/",
            1,
        )[-1]

        if filename in {
            name.lower()
            for name in SENSITIVE_FILENAMES
        }:
            if filename.startswith(
                ".env"
            ) or filename in {
                "web.config",
                "appsettings.json",
                "appsettings.production.json",
            }:
                return "configuration"

            if filename in {
                "phpinfo.php",
                "server-status",
                "server-info",
            }:
                return "debug"

            return "configuration"

        if any(
            lowered.endswith(
                extension
            )
            for extension in BACKUP_EXTENSIONS
        ):
            return "backup"

        if any(
            lowered.endswith(
                extension
            )
            for extension in SOURCE_EXTENSIONS
        ):
            return "configuration"

        if any(
            lowered == path_value
            or lowered.startswith(
                path_value
            )
            for path_value in DEBUG_PATHS
        ):
            return "debug"

        return None

    ###########################################################################
    # Severity and confidence
    ###########################################################################

    @classmethod
    def _severity_confidence(
        cls,
        *,
        classification: str,
        status_code: int | None,
        body: str,
        resource: Mapping[str, Any],
    ) -> tuple[str, str]:
        """
        Estimate severity/confidence from supplied evidence.

        This is preliminary assessment metadata. Final risk classification
        belongs to the ScopeForgeX risk engine.
        """

        body_present = bool(
            _text(
                body
            )
        )

        successful_response = (
            status_code is not None
            and 200 <= status_code < 300
        )

        explicit_access = bool(
            resource.get(
                "accessible"
            ) is True
            or resource.get(
                "exposed"
            ) is True
        )

        if classification in {
            "source_control",
            "configuration",
            "backup",
        }:
            if successful_response or explicit_access:
                return (
                    "High",
                    "High",
                )

            return (
                "Medium",
                "Medium",
            )

        if classification == "directory_listing":
            return (
                "Low",
                "High",
            )

        if classification == "debug":
            if successful_response or body_present:
                return (
                    "Medium",
                    "High",
                )

            return (
                "Low",
                "Medium",
            )

        return (
            "Medium",
            "Medium",
        )

    ###########################################################################
    # Titles and descriptions
    ###########################################################################

    @staticmethod
    def _title(
        classification: str,
        path: str,
    ) -> str:
        """Build a concise finding title."""

        titles = {
            "source_control": "Source-Control Metadata Exposed",
            "configuration": "Sensitive Configuration Resource Exposed",
            "backup": "Backup or Archive File Exposed",
            "debug": "Debug or Diagnostic Resource Exposed",
            "directory_listing": "Directory Listing Exposed",
        }

        base = titles.get(
            classification,
            "Potentially Sensitive Resource Exposed",
        )

        return (
            f"{base}: {path}"
        )

    @staticmethod
    def _description(
        *,
        classification: str,
        path: str,
        status_code: int | None,
    ) -> str:
        """Build a finding description."""

        status_text = (
            f" HTTP status: {status_code}."
            if status_code is not None
            else ""
        )

        descriptions = {
            "source_control": (
                "A source-control metadata resource was identified at "
                f"{path}.{status_text}"
            ),
            "configuration": (
                "A potentially sensitive configuration resource was "
                f"identified at {path}.{status_text}"
            ),
            "backup": (
                "A potentially sensitive backup or archive resource was "
                f"identified at {path}.{status_text}"
            ),
            "debug": (
                "A potentially sensitive debug or diagnostic resource was "
                f"identified at {path}.{status_text}"
            ),
            "directory_listing": (
                f"Directory listing indicators were identified for {path}."
            ),
        }

        return descriptions.get(
            classification,
            (
                f"A potentially sensitive resource was identified at "
                f"{path}.{status_text}"
            ),
        )

    ###########################################################################
    # Response helpers
    ###########################################################################

    @staticmethod
    def _status_code(
        resource: Mapping[str, Any],
    ) -> int | None:
        """Extract an HTTP status code from common evidence formats."""

        for key in (
            "status_code",
            "status",
        ):
            value = resource.get(
                key
            )

            if value is not None:
                parsed = _safe_int(
                    value
                )

                if parsed is not None:
                    return parsed

        response = resource.get(
            "response"
        )

        if isinstance(
            response,
            Mapping,
        ):
            for key in (
                "status_code",
                "status",
            ):
                parsed = _safe_int(
                    response.get(
                        key
                    )
                )

                if parsed is not None:
                    return parsed

        return None

    @staticmethod
    def _response_body(
        resource: Mapping[str, Any],
    ) -> str:
        """Extract response body text from common evidence formats."""

        for key in (
            "body",
            "response_body",
            "content",
        ):
            value = resource.get(
                key
            )

            if value is not None:
                return _text(
                    value
                )

        response = resource.get(
            "response"
        )

        if isinstance(
            response,
            Mapping,
        ):
            for key in (
                "body",
                "response_body",
                "content",
            ):
                value = response.get(
                    key
                )

                if value is not None:
                    return _text(
                        value
                    )

        return ""

    @staticmethod
    def _content_type(
        resource: Mapping[str, Any],
    ) -> str | None:
        """Extract a response content type."""

        value = resource.get(
            "content_type"
        )

        if value:
            return _text(
                value
            )

        headers = resource.get(
            "headers"
        )

        if isinstance(
            headers,
            Mapping,
        ):
            for key, header_value in headers.items():
                if str(
                    key
                ).lower() == "content-type":
                    return _text(
                        header_value
                    )

        return None

    @staticmethod
    def _safe_body_preview(
        body: str,
        limit: int = 500,
    ) -> str | None:
        """
        Preserve limited response evidence without attempting to extract
        secrets.
        """

        if not body:
            return None

        preview = body.strip()

        if len(preview) > limit:
            return (
                preview[:limit]
                + "..."
            )

        return preview

    @staticmethod
    def _is_directory_listing(
        body: str,
    ) -> bool:
        """Detect explicit directory-listing indicators."""

        if not body:
            return False

        lowered = body.lower()

        return any(
            marker in lowered
            for marker in DIRECTORY_LISTING_MARKERS
        )

    ###########################################################################
    # Target/path helpers
    ###########################################################################

    @staticmethod
    def _extract_path(
        url: str | None,
    ) -> str | None:
        """Extract a URL path."""

        if not url:
            return None

        try:
            parsed = urlsplit(
                url
            )

            return (
                parsed.path
                or "/"
            )
        except ValueError:
            return None

    @staticmethod
    def _normalize_path(
        path: str,
    ) -> str:
        """Normalize a resource path without altering its meaning."""

        normalized = _text(
            path
        )

        if not normalized:
            return "/"

        if not normalized.startswith(
            "/"
        ):
            normalized = (
                "/"
                + normalized
            )

        return normalized

    ###########################################################################
    # Deduplication
    ###########################################################################

    @staticmethod
    def _deduplicate(
        observations: list[SensitiveFileObservation],
    ) -> list[SensitiveFileObservation]:
        """Remove duplicate resource observations."""

        unique: list[SensitiveFileObservation] = []

        seen: set[tuple[str, str, str]] = set()

        for observation in observations:

            fingerprint = (
                observation.target,
                observation.path or "",
                observation.resource_type or "",
            )

            if fingerprint in seen:
                continue

            seen.add(
                fingerprint
            )

            unique.append(
                observation
            )

        return unique


###############################################################################
# Generic helpers
###############################################################################


def _text(value: Any) -> str:
    """Return normalized text."""

    if value is None:
        return ""

    return str(
        value
    ).strip()


def _safe_int(value: Any) -> int | None:
    """Convert a value to an integer when possible."""

    if value is None:
        return None

    try:
        return int(
            value
        )
    except (
        TypeError,
        ValueError,
    ):
        return None


###############################################################################
# Compatibility alias
###############################################################################


Analyzer = SensitiveFilesAnalyzer


###############################################################################
# Public API
###############################################################################


__all__ = [
    "SensitiveFilesAnalyzer",
    "SensitiveFileObservation",
    "Analyzer",
    "ANALYZER_NAME",
    "CATEGORY",
    "DETECTION_METHOD",
]
