"""
ScopeForgeX Runtime Events
==========================

Runtime event definitions.

Events provide the execution audit trail for:
- workflow lifecycle
- stage execution
- tool execution
- artifact creation
- findings
- warnings
- errors

v1.0
"""

from __future__ import annotations

from dataclasses import dataclass, field
from datetime import datetime, timezone
from typing import Any
from uuid import UUID


###############################################################################
# Helpers
###############################################################################


def utc_now() -> datetime:
    """
    Return current UTC timestamp.
    """

    return datetime.now(
        timezone.utc
    )


###############################################################################
# Base Event
###############################################################################


@dataclass(slots=True)
class RuntimeEvent:
    """
    Base runtime event.

    Timestamp and metadata are keyword-only to avoid dataclass inheritance
    ordering issues.
    """

    timestamp: datetime = field(
        default_factory=utc_now,
        kw_only=True,
    )

    metadata: dict[str, Any] = field(
        default_factory=dict,
        kw_only=True,
    )


###############################################################################
# Workflow Events
###############################################################################


@dataclass(slots=True)
class WorkflowStartedEvent(RuntimeEvent):
    """
    Workflow execution started.
    """

    workflow_id: UUID
    target: str
    profile: str


@dataclass(slots=True)
class WorkflowFinishedEvent(RuntimeEvent):
    """
    Workflow execution finished.
    """

    workflow_id: UUID
    success: bool


###############################################################################
# Stage Events
###############################################################################


@dataclass(slots=True)
class StageStartedEvent(RuntimeEvent):
    """
    Stage execution started.
    """

    stage: str


@dataclass(slots=True)
class StageFinishedEvent(RuntimeEvent):
    """
    Stage execution completed.
    """

    stage: str
    success: bool


###############################################################################
# Tool Events
###############################################################################


@dataclass(slots=True)
class ToolStartedEvent(RuntimeEvent):
    """
    Tool execution started.
    """

    tool: str
    capability: str


@dataclass(slots=True)
class ToolFinishedEvent(RuntimeEvent):
    """
    Tool execution completed.
    """

    tool: str
    success: bool
    duration: float


###############################################################################
# Artifact Events
###############################################################################


@dataclass(slots=True)
class ArtifactCreatedEvent(RuntimeEvent):
    """
    Artifact generated by a capability.
    """

    path: str


###############################################################################
# Finding Events
###############################################################################


@dataclass(slots=True)
class FindingRecordedEvent(RuntimeEvent):
    """
    Vulnerability or security finding recorded.
    """

    finding: str
    severity: str = "unknown"


###############################################################################
# Diagnostic Events
###############################################################################


@dataclass(slots=True)
class WarningRecordedEvent(RuntimeEvent):
    """
    Runtime warning recorded.
    """

    message: str


@dataclass(slots=True)
class ErrorRecordedEvent(RuntimeEvent):
    """
    Runtime error recorded.
    """

    message: str


###############################################################################
# Public Exports
###############################################################################


__all__ = [
    "RuntimeEvent",
    "WorkflowStartedEvent",
    "WorkflowFinishedEvent",
    "StageStartedEvent",
    "StageFinishedEvent",
    "ToolStartedEvent",
    "ToolFinishedEvent",
    "ArtifactCreatedEvent",
    "FindingRecordedEvent",
    "WarningRecordedEvent",
    "ErrorRecordedEvent",
]
